In [267]:
# !pip install bs4
# !pip install lxml
# !pip install selenium
# !pip install pandas

In [2]:
import re
import pandas as pd

In [269]:
file_name = 'parsed_data.tsv'
df = pd.read_csv(file_name, sep='\t')
df

,"Диагональ экрана, дюймы",Разрешение,"Потребляемая мощность, Вт",Назначение монитора,Число портов HDMI,Разъёмы монитора,Установка монитора,Регулировки,"Размеры, мм","Вес, кг",...,"Плотность пикселей, ppi",Технология HDR,Cтандарты HDR,Количество USB портов,Стандарт крепления VESA,Уровни регулировки подставки,"Срок службы, лет","Размер пикселя, мм",Гарантия OZON,Конструктивные особенности
0,34.0,3440x1440 Ultra WQHD,24.0,"Для дизайна,Для дома и офиса,Для игр,Для работ...",2.0,"DisplayPort,3.5 мм,HDMI",На подставку,"Вращение,Наклон,Поворот,Регулируемая высота",811/510/210,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,27.0,1920x1080 Full HD,NaN,"Для игр,Для дома и офиса,Для дизайна,Для работ...",1.0,"3.5 мм,DisplayPort,HDMI",На подставку,Наклон,452 х 612 х 185,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,24.0,1920x1080 Full HD,30.0,"Для дизайна,Для дома и офиса,Для игр,Для работ...",1.0,"DisplayPort,HDMI,USB Type-B",На подставку,Наклон,NaN,3.5,...,108.0,Да,HDR10,1.0,75x75 мм,22,5.0,NaN,NaN,NaN
3,23.8,1920x1080 Full HD,30.0,"Для дома и офиса,Для игр,Для работы с графикой...",1.0,"HDMI,VGA (D-SUB),DisplayPort","На подставку,Крепление на стену",Наклон,NaN,3.0,...,NaN,Нет,NaN,NaN,75x75 мм,3,NaN,NaN,NaN,NaN
4,27.0,1920x1080 Full HD,35.0,"Для дизайна,Для дома и офиса,Для игр,Для работ...",NaN,"HDMI,VGA (D-SUB)","Крепление на стену,На подставку",NaN,NaN,4.0,...,NaN,Да,NaN,NaN,NaN,NaN,NaN,0.3114,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3841,27.0,2560x1440 2K,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3842,31.5,1920x1080,30.0,Для дома и офиса,2.0,"HDMI,3.5 мм,VGA (D-SUB)","На подставку,Крепление на стену",NaN,715 x 514 x 248,7.5,...,NaN,NaN,NaN,NaN,100x100 мм,NaN,NaN,NaN,NaN,NaN
3843,32.0,2560x1440 2K,33.0,"Для дизайна,Для дома и офиса,Для игр",1.0,"DisplayPort,HDMI","Крепление на стену,На подставку","Вращение,Регулируемая высота,Наклон",785*120*505,6.6,...,100.0,Да,HDR10,1.0,100x100 мм,Горизонтальный/вертикальный,NaN,0.02,NaN,USB-хаб
3844,23.8,1920x1080,36.0,Для дома и офиса,1.0,"HDMI,DisplayPort,3.5 мм,USB Type-A,VGA (D-SUB)","На подставку,Крепление на стену","Наклон,Поворот,Регулируемая высота",NaN,3.7,...,NaN,NaN,NaN,1.0,100x100 мм,NaN,NaN,NaN,NaN,Web-камера
3845,21.5,1920x1080 Full HD,NaN,Для дома и офиса,2.0,"VGA (D-SUB),HDMI",На подставку,Наклон,489.5 х 391.6 х 183,5.0,...,102.0,Нет,NaN,NaN,100x100 мм,-5°/+20°,NaN,0.247,NaN,NaN

### Преобразуем столбец Разрешение

In [270]:
df['Разрешение'].unique()

array(['3440x1440 Ultra WQHD', '1920x1080 Full HD', '1920x1080',
       '5120x1440', '1440x900 WXGA+', '3840x2160 4K', '2560x1440 2K',
       '5120x2880 5K', '2560x1080', '3840x1080', '1024x600',
       '1920x1200 WUXGA', '2560x1920', '1600x900 HD+', '2560x1600 WQXGA',
       '7680x2160', '3840x1600 UW4K', '1366x768 HD', '1280x1024 SXGA',
       '1280x720 HD', '3840x2560', '1920x550', '1366x768 WXGA',
       '1920x490', '1080P', '480x272', '1280x800', '2560x1944',
       '1680x1050 HD', nan, '1366x768 FHD', '5120x2160', '800x480 WVGA'],
      dtype=object)

In [271]:
known_resolutions = {
    '1080P': '1920x1080',
}

def replace_known_resolutions(value):
    for key, resolution in known_resolutions.items():
        if key in value:
            return resolution
    return value

df['Разрешение'] = df['Разрешение'].fillna('')
df['Разрешение'] = df['Разрешение'].apply(replace_known_resolutions)

df[['Ширина, пиксели', 'Высота, пиксели']] = df['Разрешение'].str.extract(r'(\d{3,5})x(\d{3,5})')

df['Ширина, пиксели'] = pd.to_numeric(df['Ширина, пиксели'], errors='coerce')
df['Высота, пиксели'] = pd.to_numeric(df['Высота, пиксели'], errors='coerce')

df = df.drop(columns=['Разрешение'])
df.to_csv('step1_resolution.tsv', sep='\t', index=False)
df

,"Диагональ экрана, дюймы","Потребляемая мощность, Вт",Назначение монитора,Число портов HDMI,Разъёмы монитора,Установка монитора,Регулировки,"Размеры, мм","Вес, кг",Матрица монитора,...,Cтандарты HDR,Количество USB портов,Стандарт крепления VESA,Уровни регулировки подставки,"Срок службы, лет","Размер пикселя, мм",Гарантия OZON,Конструктивные особенности,"Ширина, пиксели","Высота, пиксели"
0,34.0,24.0,"Для дизайна,Для дома и офиса,Для игр,Для работ...",2.0,"DisplayPort,3.5 мм,HDMI",На подставку,"Вращение,Наклон,Поворот,Регулируемая высота",811/510/210,6.0,VA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3440.0,1440.0
1,27.0,NaN,"Для игр,Для дома и офиса,Для дизайна,Для работ...",1.0,"3.5 мм,DisplayPort,HDMI",На подставку,Наклон,452 х 612 х 185,4.0,IPS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1920.0,1080.0
2,24.0,30.0,"Для дизайна,Для дома и офиса,Для игр,Для работ...",1.0,"DisplayPort,HDMI,USB Type-B",На подставку,Наклон,NaN,3.5,VA,...,HDR10,1.0,75x75 мм,22,5.0,NaN,NaN,NaN,1920.0,1080.0
3,23.8,30.0,"Для дома и офиса,Для игр,Для работы с графикой...",1.0,"HDMI,VGA (D-SUB),DisplayPort","На подставку,Крепление на стену",Наклон,NaN,3.0,IPS,...,NaN,NaN,75x75 мм,3,NaN,NaN,NaN,NaN,1920.0,1080.0
4,27.0,35.0,"Для дизайна,Для дома и офиса,Для игр,Для работ...",NaN,"HDMI,VGA (D-SUB)","Крепление на стену,На подставку",NaN,NaN,4.0,IPS,...,NaN,NaN,NaN,NaN,NaN,0.3114,NaN,NaN,1920.0,1080.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3841,27.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2560.0,1440.0
3842,31.5,30.0,Для дома и офиса,2.0,"HDMI,3.5 мм,VGA (D-SUB)","На подставку,Крепление на стену",NaN,715 x 514 x 248,7.5,IPS,...,NaN,NaN,100x100 мм,NaN,NaN,NaN,NaN,NaN,1920.0,1080.0
3843,32.0,33.0,"Для дизайна,Для дома и офиса,Для игр",1.0,"DisplayPort,HDMI","Крепление на стену,На подставку","Вращение,Регулируемая высота,Наклон",785*120*505,6.6,VA,...,HDR10,1.0,100x100 мм,Горизонтальный/вертикальный,NaN,0.02,NaN,USB-хаб,2560.0,1440.0
3844,23.8,36.0,Для дома и офиса,1.0,"HDMI,DisplayPort,3.5 мм,USB Type-A,VGA (D-SUB)","На подставку,Крепление на стену","Наклон,Поворот,Регулируемая высота",NaN,3.7,IPS,...,NaN,1.0,100x100 мм,NaN,NaN,NaN,NaN,Web-камера,1920.0,1080.0
3845,21.5,NaN,Для дома и офиса,2.0,"VGA (D-SUB),HDMI",На подставку,Наклон,489.5 х 391.6 х 183,5.0,IPS,...,NaN,NaN,100x100 мм,-5°/+20°,NaN,0.247,NaN,NaN,1920.0,1080.0

### Далее будем разбивать столбец Назначение монитора

In [272]:
df = pd.read_csv('step1_resolution.tsv', sep='\t')
df['Назначение монитора'].unique()

array(['Для дизайна,Для дома и офиса,Для игр,Для работы с графикой',
       'Для игр,Для дома и офиса,Для дизайна,Для работы с графикой',
       'Для дома и офиса,Для игр,Для работы с графикой,Для дизайна',
       'Для дома и офиса',
       'Для работы с графикой,Для игр,Для дома и офиса,Для дизайна',
       'Для дома и офиса,Для дизайна,Для работы с графикой,Для игр',
       'Для дома и офиса,Для дизайна,Для работы с графикой',
       'Для дома и офиса,Для игр,Для дизайна,Для работы с графикой',
       'Для дома и офиса,Для дизайна', 'Для дома и офиса,Для игр',
       'Для игр',
       'Для игр,Для дома и офиса,Для работы с графикой,Для дизайна',
       'Для игр,Для дома и офиса',
       'Для дизайна,Для дома и офиса,Для работы с графикой',
       'Для игр,Для работы с графикой,Для дизайна',
       'Для игр,Для дизайна,Для дома и офиса,Для работы с графикой',
       'Для дизайна,Для игр,Для работы с графикой,Для дома и офиса',
       'Для работы с графикой,Для дизайна,Для дома и офиса',
       'Для дизайна,Для игр,Для дома и офиса,Для работы с графикой',
       'Для игр,Для работы с графикой,Для дома и офиса',
       'Для дизайна,Для дома и офиса,Для игр',
       'Для игр,Для работы с графикой', nan,
       'Для игр,Для дизайна,Для работы с графикой',
       'Для дома и офиса,Для дизайна,Для игр,Для работы с графикой',
       'Для игр,Для дома и офиса,Для работы с графикой',
       'Для дома и офиса,Для игр,Для работы с графикой',
       'Для игр,Для дома и офиса,Для дизайна',
       'Для дизайна,Для игр,Для дома и офиса',
       'Для игр,Для работы с графикой,Для дома и офиса,Для дизайна',
       'Для игр,Для дизайна',
       'Для игр,Для работы с графикой,Для дизайна,Для дома и офиса',
       'Для дома и офиса,Для работы с графикой,Для дизайна',
       'Для игр,Для дизайна,Для работы с графикой,Для дома и офиса',
       'Для дизайна,Для игр,Для работы с графикой',
       'Для дизайна,Для дома и офиса',
       'Для дома и офиса,Для работы с графикой,Для дизайна,Для игр',
       'Для дома и офиса,Для работы с графикой,Для игр,Для дизайна',
       'Для дизайна,Для дома и офиса,Для работы с графикой,Для игр',
       'Для дизайна,Для игр',
       'Для работы с графикой,Для дизайна,Для дома и офиса,Для игр',
       'Для работы с графикой',
       'Для работы с графикой,Для игр,Для дизайна,Для дома и офиса',
       'Для дома и офиса,Для работы с графикой',
       'Для работы с графикой,Для дома и офиса,Для дизайна',
       'Для дома и офиса,Для дизайна,Для игр',
       'Для дома и офиса,Для игр,Для дизайна',
       'Для работы с графикой,Для дизайна', 'Для дизайна',
       'Для дизайна,Для работы с графикой',
       'Для работы с графикой,Для дома и офиса',
       'Для работы с графикой,Для дома и офиса,Для игр,Для дизайна'],
      dtype=object)

In [273]:
df['Назначение монитора'] = df['Назначение монитора'].str.split(',')
df['NaN_Назначение'] = df['Назначение монитора'].isna()

df_exploded = df.explode('Назначение монитора')
df_encoded = pd.get_dummies(df_exploded, columns=['Назначение монитора'])

aggregation_dict = {}
for col in df_encoded.columns:
    if 'Назначение монитора' in col:
        aggregation_dict[col] = 'max'
    else:
        aggregation_dict[col] = 'first'

df_final = df_encoded.groupby(level=0).agg(aggregation_dict)

for col in df_final.columns:
    if 'Назначение монитора' in col:
        df_final[col] = df_final[col].where(~df['NaN_Назначение'], None)
df_final = df_final.drop(columns='NaN_Назначение')

df_final.to_csv('step2_usage.tsv', sep='\t', index=False)

df_final

,"Диагональ экрана, дюймы","Потребляемая мощность, Вт",Число портов HDMI,Разъёмы монитора,Установка монитора,Регулировки,"Размеры, мм","Вес, кг",Матрица монитора,"Макс. частота обновления, Гц",...,"Срок службы, лет","Размер пикселя, мм",Гарантия OZON,Конструктивные особенности,"Ширина, пиксели","Высота, пиксели",Назначение монитора_Для дизайна,Назначение монитора_Для дома и офиса,Назначение монитора_Для игр,Назначение монитора_Для работы с графикой
0,34.0,24.0,2.0,"DisplayPort,3.5 мм,HDMI",На подставку,"Вращение,Наклон,Поворот,Регулируемая высота",811/510/210,6.0,VA,180.0,...,NaN,None,None,None,3440.0,1440.0,True,True,True,True
1,27.0,NaN,1.0,"3.5 мм,DisplayPort,HDMI",На подставку,Наклон,452 х 612 х 185,4.0,IPS,165.0,...,NaN,None,None,None,1920.0,1080.0,True,True,True,True
2,24.0,30.0,1.0,"DisplayPort,HDMI,USB Type-B",На подставку,Наклон,None,3.5,VA,180.0,...,5.0,None,None,None,1920.0,1080.0,True,True,True,True
3,23.8,30.0,1.0,"HDMI,VGA (D-SUB),DisplayPort","На подставку,Крепление на стену",Наклон,None,3.0,IPS,100.0,...,NaN,None,None,None,1920.0,1080.0,True,True,True,True
4,27.0,35.0,NaN,"HDMI,VGA (D-SUB)","Крепление на стену,На подставку",None,None,4.0,IPS,75.0,...,NaN,0.3114,None,None,1920.0,1080.0,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3841,27.0,NaN,NaN,None,None,None,None,NaN,None,NaN,...,NaN,None,None,None,2560.0,1440.0,None,None,None,None
3842,31.5,30.0,2.0,"HDMI,3.5 мм,VGA (D-SUB)","На подставку,Крепление на стену",None,715 x 514 x 248,7.5,IPS,75.0,...,NaN,None,None,None,1920.0,1080.0,False,True,False,False
3843,32.0,33.0,1.0,"DisplayPort,HDMI","Крепление на стену,На подставку","Вращение,Регулируемая высота,Наклон",785*120*505,6.6,VA,165.0,...,NaN,0.02,None,USB-хаб,2560.0,1440.0,True,True,True,False
3844,23.8,36.0,1.0,"HDMI,DisplayPort,3.5 мм,USB Type-A,VGA (D-SUB)","На подставку,Крепление на стену","Наклон,Поворот,Регулируемая высота",None,3.7,IPS,75.0,...,NaN,None,None,Web-камера,1920.0,1080.0,False,True,False,False
3845,21.5,NaN,2.0,"VGA (D-SUB),HDMI",На подставку,Наклон,489.5 х 391.6 х 183,5.0,IPS,60.0,...,NaN,0.247,None,None,1920.0,1080.0,False,True,False,False

### Преобразуем столбец для типа матрицы

In [274]:
df = pd.read_csv('step2_usage.tsv', sep='\t')
df['Матрица монитора'].value_counts()

Матрица монитора
IPS     2343
VA      1114
OLED      73
TN        61
TFT        5
PLS        3
Name: count, dtype: int64

In [275]:
df_matrix_encoded = pd.get_dummies(df['Матрица монитора'], prefix='Матрица', dummy_na=True)

df_final = pd.concat([df, df_matrix_encoded], axis=1)

df_final.drop('Матрица монитора', axis=1, inplace=True)

df_final.to_csv('step3_matrix.tsv', sep='\t', index=False)

df_final

,"Диагональ экрана, дюймы","Потребляемая мощность, Вт",Число портов HDMI,Разъёмы монитора,Установка монитора,Регулировки,"Размеры, мм","Вес, кг","Макс. частота обновления, Гц",Изогнутый экран,...,Назначение монитора_Для дома и офиса,Назначение монитора_Для игр,Назначение монитора_Для работы с графикой,Матрица_IPS,Матрица_OLED,Матрица_PLS,Матрица_TFT,Матрица_TN,Матрица_VA,Матрица_nan
0,34.0,24.0,2.0,"DisplayPort,3.5 мм,HDMI",На подставку,"Вращение,Наклон,Поворот,Регулируемая высота",811/510/210,6.0,180.0,Да,...,True,True,True,False,False,False,False,False,True,False
1,27.0,NaN,1.0,"3.5 мм,DisplayPort,HDMI",На подставку,Наклон,452 х 612 х 185,4.0,165.0,Нет,...,True,True,True,True,False,False,False,False,False,False
2,24.0,30.0,1.0,"DisplayPort,HDMI,USB Type-B",На подставку,Наклон,NaN,3.5,180.0,Нет,...,True,True,True,False,False,False,False,False,True,False
3,23.8,30.0,1.0,"HDMI,VGA (D-SUB),DisplayPort","На подставку,Крепление на стену",Наклон,NaN,3.0,100.0,Нет,...,True,True,True,True,False,False,False,False,False,False
4,27.0,35.0,NaN,"HDMI,VGA (D-SUB)","Крепление на стену,На подставку",NaN,NaN,4.0,75.0,Нет,...,True,True,True,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3841,27.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,False,False,False,False,False,False,True
3842,31.5,30.0,2.0,"HDMI,3.5 мм,VGA (D-SUB)","На подставку,Крепление на стену",NaN,715 x 514 x 248,7.5,75.0,Нет,...,True,False,False,True,False,False,False,False,False,False
3843,32.0,33.0,1.0,"DisplayPort,HDMI","Крепление на стену,На подставку","Вращение,Регулируемая высота,Наклон",785*120*505,6.6,165.0,Да,...,True,True,False,False,False,False,False,False,True,False
3844,23.8,36.0,1.0,"HDMI,DisplayPort,3.5 мм,USB Type-A,VGA (D-SUB)","На подставку,Крепление на стену","Наклон,Поворот,Регулируемая высота",NaN,3.7,75.0,Нет,...,True,False,False,True,False,False,False,False,False,False
3845,21.5,NaN,2.0,"VGA (D-SUB),HDMI",На подставку,Наклон,489.5 х 391.6 х 183,5.0,60.0,Нет,...,True,False,False,True,False,False,False,False,False,False

### Преобразуем столбцы для булевых значений. Наличие Web-камеры, встроенных динамиков, изогнутый экран

In [276]:
df = pd.read_csv('step3_matrix.tsv', sep='\t')

In [277]:
print(df['Web-камера'].unique())

def webcam_presence(value):
    if pd.isna(value):
        return False
    value = str(value).strip().lower()
    if value in ['да', 'есть', 'встроенная веб-камера', '1', '12мр', '4k slimfit', 'да', '5mp', '12мр', '0.5']:
        return True
    elif value in ['нет', 'не', 'отсутствует', 'no', 'нo', 'het', 'hет', 'ytn', 'без', '0', '-', 'не иметь', 'отсутствует', '不', '无']:
        return False
    else:
        return None

df['Web-камера'] = df['Web-камера'].apply(webcam_presence)
df

['Нет' 'нет' 'не' nan '不' '0' 'Отсутствует' 'НЕТ' '1' '无' 'не иметь' 'no'
 '-' 'Ytn' 'отсутствует' 'Het' 'Hет' 'het' 'Есть' 'Да' 'No' 'NO' 'HET'
 'без' 'встроенная веб-камера' '12МР' 'ДА' '5MP' '4K SlimFit' 'да' '0.5']

,"Диагональ экрана, дюймы","Потребляемая мощность, Вт",Число портов HDMI,Разъёмы монитора,Установка монитора,Регулировки,"Размеры, мм","Вес, кг","Макс. частота обновления, Гц",Изогнутый экран,...,Назначение монитора_Для дома и офиса,Назначение монитора_Для игр,Назначение монитора_Для работы с графикой,Матрица_IPS,Матрица_OLED,Матрица_PLS,Матрица_TFT,Матрица_TN,Матрица_VA,Матрица_nan
0,34.0,24.0,2.0,"DisplayPort,3.5 мм,HDMI",На подставку,"Вращение,Наклон,Поворот,Регулируемая высота",811/510/210,6.0,180.0,Да,...,True,True,True,False,False,False,False,False,True,False
1,27.0,NaN,1.0,"3.5 мм,DisplayPort,HDMI",На подставку,Наклон,452 х 612 х 185,4.0,165.0,Нет,...,True,True,True,True,False,False,False,False,False,False
2,24.0,30.0,1.0,"DisplayPort,HDMI,USB Type-B",На подставку,Наклон,NaN,3.5,180.0,Нет,...,True,True,True,False,False,False,False,False,True,False
3,23.8,30.0,1.0,"HDMI,VGA (D-SUB),DisplayPort","На подставку,Крепление на стену",Наклон,NaN,3.0,100.0,Нет,...,True,True,True,True,False,False,False,False,False,False
4,27.0,35.0,NaN,"HDMI,VGA (D-SUB)","Крепление на стену,На подставку",NaN,NaN,4.0,75.0,Нет,...,True,True,True,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3841,27.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,False,False,False,False,False,False,True
3842,31.5,30.0,2.0,"HDMI,3.5 мм,VGA (D-SUB)","На подставку,Крепление на стену",NaN,715 x 514 x 248,7.5,75.0,Нет,...,True,False,False,True,False,False,False,False,False,False
3843,32.0,33.0,1.0,"DisplayPort,HDMI","Крепление на стену,На подставку","Вращение,Регулируемая высота,Наклон",785*120*505,6.6,165.0,Да,...,True,True,False,False,False,False,False,False,True,False
3844,23.8,36.0,1.0,"HDMI,DisplayPort,3.5 мм,USB Type-A,VGA (D-SUB)","На подставку,Крепление на стену","Наклон,Поворот,Регулируемая высота",NaN,3.7,75.0,Нет,...,True,False,False,True,False,False,False,False,False,False
3845,21.5,NaN,2.0,"VGA (D-SUB),HDMI",На подставку,Наклон,489.5 х 391.6 х 183,5.0,60.0,Нет,...,True,False,False,True,False,False,False,False,False,False

In [278]:
print(df['Встроенные динамики'].unique())

def is_present(value):
    if pd.isna(value):
        return False

    value = value.strip().lower()
    if 'да' in value:
        return True
    elif 'нет' in value:
        return False
    else:
        return None

df['Встроенные динамики'] = df['Встроенные динамики'].apply(is_present)
df

['Нет' 'Да' nan]

,"Диагональ экрана, дюймы","Потребляемая мощность, Вт",Число портов HDMI,Разъёмы монитора,Установка монитора,Регулировки,"Размеры, мм","Вес, кг","Макс. частота обновления, Гц",Изогнутый экран,...,Назначение монитора_Для дома и офиса,Назначение монитора_Для игр,Назначение монитора_Для работы с графикой,Матрица_IPS,Матрица_OLED,Матрица_PLS,Матрица_TFT,Матрица_TN,Матрица_VA,Матрица_nan
0,34.0,24.0,2.0,"DisplayPort,3.5 мм,HDMI",На подставку,"Вращение,Наклон,Поворот,Регулируемая высота",811/510/210,6.0,180.0,Да,...,True,True,True,False,False,False,False,False,True,False
1,27.0,NaN,1.0,"3.5 мм,DisplayPort,HDMI",На подставку,Наклон,452 х 612 х 185,4.0,165.0,Нет,...,True,True,True,True,False,False,False,False,False,False
2,24.0,30.0,1.0,"DisplayPort,HDMI,USB Type-B",На подставку,Наклон,NaN,3.5,180.0,Нет,...,True,True,True,False,False,False,False,False,True,False
3,23.8,30.0,1.0,"HDMI,VGA (D-SUB),DisplayPort","На подставку,Крепление на стену",Наклон,NaN,3.0,100.0,Нет,...,True,True,True,True,False,False,False,False,False,False
4,27.0,35.0,NaN,"HDMI,VGA (D-SUB)","Крепление на стену,На подставку",NaN,NaN,4.0,75.0,Нет,...,True,True,True,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3841,27.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,False,False,False,False,False,False,True
3842,31.5,30.0,2.0,"HDMI,3.5 мм,VGA (D-SUB)","На подставку,Крепление на стену",NaN,715 x 514 x 248,7.5,75.0,Нет,...,True,False,False,True,False,False,False,False,False,False
3843,32.0,33.0,1.0,"DisplayPort,HDMI","Крепление на стену,На подставку","Вращение,Регулируемая высота,Наклон",785*120*505,6.6,165.0,Да,...,True,True,False,False,False,False,False,False,True,False
3844,23.8,36.0,1.0,"HDMI,DisplayPort,3.5 мм,USB Type-A,VGA (D-SUB)","На подставку,Крепление на стену","Наклон,Поворот,Регулируемая высота",NaN,3.7,75.0,Нет,...,True,False,False,True,False,False,False,False,False,False
3845,21.5,NaN,2.0,"VGA (D-SUB),HDMI",На подставку,Наклон,489.5 х 391.6 х 183,5.0,60.0,Нет,...,True,False,False,True,False,False,False,False,False,False

In [279]:
print(df['Изогнутый экран'].unique())

df['Изогнутый экран'] = df['Изогнутый экран'].apply(is_present)
df

['Да' 'Нет' nan]

,"Диагональ экрана, дюймы","Потребляемая мощность, Вт",Число портов HDMI,Разъёмы монитора,Установка монитора,Регулировки,"Размеры, мм","Вес, кг","Макс. частота обновления, Гц",Изогнутый экран,...,Назначение монитора_Для дома и офиса,Назначение монитора_Для игр,Назначение монитора_Для работы с графикой,Матрица_IPS,Матрица_OLED,Матрица_PLS,Матрица_TFT,Матрица_TN,Матрица_VA,Матрица_nan
0,34.0,24.0,2.0,"DisplayPort,3.5 мм,HDMI",На подставку,"Вращение,Наклон,Поворот,Регулируемая высота",811/510/210,6.0,180.0,True,...,True,True,True,False,False,False,False,False,True,False
1,27.0,NaN,1.0,"3.5 мм,DisplayPort,HDMI",На подставку,Наклон,452 х 612 х 185,4.0,165.0,False,...,True,True,True,True,False,False,False,False,False,False
2,24.0,30.0,1.0,"DisplayPort,HDMI,USB Type-B",На подставку,Наклон,NaN,3.5,180.0,False,...,True,True,True,False,False,False,False,False,True,False
3,23.8,30.0,1.0,"HDMI,VGA (D-SUB),DisplayPort","На подставку,Крепление на стену",Наклон,NaN,3.0,100.0,False,...,True,True,True,True,False,False,False,False,False,False
4,27.0,35.0,NaN,"HDMI,VGA (D-SUB)","Крепление на стену,На подставку",NaN,NaN,4.0,75.0,False,...,True,True,True,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3841,27.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,...,NaN,NaN,NaN,False,False,False,False,False,False,True
3842,31.5,30.0,2.0,"HDMI,3.5 мм,VGA (D-SUB)","На подставку,Крепление на стену",NaN,715 x 514 x 248,7.5,75.0,False,...,True,False,False,True,False,False,False,False,False,False
3843,32.0,33.0,1.0,"DisplayPort,HDMI","Крепление на стену,На подставку","Вращение,Регулируемая высота,Наклон",785*120*505,6.6,165.0,True,...,True,True,False,False,False,False,False,False,True,False
3844,23.8,36.0,1.0,"HDMI,DisplayPort,3.5 мм,USB Type-A,VGA (D-SUB)","На подставку,Крепление на стену","Наклон,Поворот,Регулируемая высота",NaN,3.7,75.0,False,...,True,False,False,True,False,False,False,False,False,False
3845,21.5,NaN,2.0,"VGA (D-SUB),HDMI",На подставку,Наклон,489.5 х 391.6 х 183,5.0,60.0,False,...,True,False,False,True,False,False,False,False,False,False

In [280]:
df.to_csv('step4_bool.tsv', sep='\t', index=False)

### Преобразуем контрастность

In [281]:
df = pd.read_csv('step4_bool.tsv', sep='\t')
df

,"Диагональ экрана, дюймы","Потребляемая мощность, Вт",Число портов HDMI,Разъёмы монитора,Установка монитора,Регулировки,"Размеры, мм","Вес, кг","Макс. частота обновления, Гц",Изогнутый экран,...,Назначение монитора_Для дома и офиса,Назначение монитора_Для игр,Назначение монитора_Для работы с графикой,Матрица_IPS,Матрица_OLED,Матрица_PLS,Матрица_TFT,Матрица_TN,Матрица_VA,Матрица_nan
0,34.0,24.0,2.0,"DisplayPort,3.5 мм,HDMI",На подставку,"Вращение,Наклон,Поворот,Регулируемая высота",811/510/210,6.0,180.0,True,...,True,True,True,False,False,False,False,False,True,False
1,27.0,NaN,1.0,"3.5 мм,DisplayPort,HDMI",На подставку,Наклон,452 х 612 х 185,4.0,165.0,False,...,True,True,True,True,False,False,False,False,False,False
2,24.0,30.0,1.0,"DisplayPort,HDMI,USB Type-B",На подставку,Наклон,NaN,3.5,180.0,False,...,True,True,True,False,False,False,False,False,True,False
3,23.8,30.0,1.0,"HDMI,VGA (D-SUB),DisplayPort","На подставку,Крепление на стену",Наклон,NaN,3.0,100.0,False,...,True,True,True,True,False,False,False,False,False,False
4,27.0,35.0,NaN,"HDMI,VGA (D-SUB)","Крепление на стену,На подставку",NaN,NaN,4.0,75.0,False,...,True,True,True,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3841,27.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,...,NaN,NaN,NaN,False,False,False,False,False,False,True
3842,31.5,30.0,2.0,"HDMI,3.5 мм,VGA (D-SUB)","На подставку,Крепление на стену",NaN,715 x 514 x 248,7.5,75.0,False,...,True,False,False,True,False,False,False,False,False,False
3843,32.0,33.0,1.0,"DisplayPort,HDMI","Крепление на стену,На подставку","Вращение,Регулируемая высота,Наклон",785*120*505,6.6,165.0,True,...,True,True,False,False,False,False,False,False,True,False
3844,23.8,36.0,1.0,"HDMI,DisplayPort,3.5 мм,USB Type-A,VGA (D-SUB)","На подставку,Крепление на стену","Наклон,Поворот,Регулируемая высота",NaN,3.7,75.0,False,...,True,False,False,True,False,False,False,False,False,False
3845,21.5,NaN,2.0,"VGA (D-SUB),HDMI",На подставку,Наклон,489.5 х 391.6 х 183,5.0,60.0,False,...,True,False,False,True,False,False,False,False,False,False

In [282]:
df['Контрастность'].unique()

array(['3000', '1000/1', '10000:1', '1100:1', nan, '1000:1', '3500:1',
       '1000000:1', '3 000 : 1', '4000:1', '3000:1', '1 000 : 1',
       '5000:1', '1000', '4250:1', '3 000:1', '3000：1', '1', '4 000:1',
       '1200：1', '4 000 : 1', '4000', '1200:1', '3 500 : 1', '3000.:1',
       '1000 : 1', '2500:1', '1000 :1', '1200', '1000: 1', '150000:1',
       '1200 к 1', '1100', '100000:1', '800', '1 000 :1', '2500',
       '1000：1', '1 200 : 1', '650:1', '1 000:1', '600:1', '1 300\xa0:1',
       '1300:1', '1300', '1: 1000', '5', '41.667361111111113', '5 000:1',
       '1: 1300', '30000:1', '1000:1(Typical)', '5000', '800:1', '2000:1',
       '1 200:1', '1,000:1', '1400:1', '1 000\xa0:1', '700', '10001:1',
       '1 200\xa0:1', '4 000\xa0:1', '3 000\xa0:1', '3 500\xa0:1',
       '3500：1', '1500:1', '700\xa0:1', '1 500 000\xa0:1', '2 000 : 1',
       '1500000:1', '1200 :1', 'Контрастность', '600 : 1', '3000 : 1',
       '1000 к 1', '300:1', '1500：1', '1500', '700:1', '2000 : 1', '300',
       '4000 : 1', '25000:1', '3000: 1', '5 000\xa0:1', '3000.0 :1',
       '5000: 1', '600', '3000 к 1', '1:3000'], dtype=object)

In [283]:
df['Динамическая контрастность'].unique()

array([nan, '10000:1', 'статическая', '1000:1', '1：1000',
       '10 000 000 : 1', '300000:1', '3500:1', '3000:1', 'DCR',
       '10000000', '1000000:1', 'Mega DCR', '100000:1', '10000000 : 1',
       '10000000:1', '100000000:1', '80M:1', '3000：1', '1300:1',
       '3000000', '80М:1', 'да', '40000000:1', 'Mega Infinity DCR',
       '1000:!', '1000：1', '100000000：1', '1500：1', 'Mega', '10M:1',
       '700:1', '100М:1', '4000：1', '100000000 к 1', 'MEGA DCR',
       '5000000:1', '5 000 000 :1', '1000: 1', '4000:1', '1500000:1',
       '50000000:1', '1:1000', '50000000：1', '100000000', '5000000',
       '12000000', '1000000', '3 М :1', '3000000:1', '500000', '5000:1',
       '20000000:1', '200M:1', '100 000 000:1', '20M:1', '5000：1',
       '12000000:1', '10М:1', '80 000 000:1', '1 : 2000000', '50000:1',
       '80000000', '500000:1', '80 000 000', '100M:1', '80000000:1',
       'MEGA', '100 000 000', 'нет', '1 : 10000000', '5000', '100000',
       '100000000:2', '8000000', '50000000', '8M:1', '20 000 000:1',
       '80m:1', '100000000/1', '1500:1', '10 000 000:1', '3000 : 1',
       '50M:1', '2000:1', 'более 1 млрд.', '100,000,000:1', '800:1',
       '1:1000000', '8000W：1', '12М:1', '10000000 :1', '1000', '1200:1',
       '200000:1', '3М:1', '1 000 000:1', '50 000 000:1', '50M: 1',
       '1M:1'], dtype=object)

In [284]:
def parse_contrast(value):
    if pd.isna(value):
        return None

    value = value.lower().replace(' ', '').replace('m', '000000').replace('м', '000000')

    value = re.sub(r'[^\d\.:]', '', value)

    parts = re.split(r':|：|/|к', value)
    numbers = [int(p) for p in parts if p.isdigit()]

    return max(numbers) if numbers else None

df['Контрастность'] = df['Контрастность'].apply(parse_contrast)
df['Динамическая контрастность'] = df['Динамическая контрастность'].apply(parse_contrast)

df.to_csv('step5_contrast.tsv', sep='\t', index=False)

df

,"Диагональ экрана, дюймы","Потребляемая мощность, Вт",Число портов HDMI,Разъёмы монитора,Установка монитора,Регулировки,"Размеры, мм","Вес, кг","Макс. частота обновления, Гц",Изогнутый экран,...,Назначение монитора_Для дома и офиса,Назначение монитора_Для игр,Назначение монитора_Для работы с графикой,Матрица_IPS,Матрица_OLED,Матрица_PLS,Матрица_TFT,Матрица_TN,Матрица_VA,Матрица_nan
0,34.0,24.0,2.0,"DisplayPort,3.5 мм,HDMI",На подставку,"Вращение,Наклон,Поворот,Регулируемая высота",811/510/210,6.0,180.0,True,...,True,True,True,False,False,False,False,False,True,False
1,27.0,NaN,1.0,"3.5 мм,DisplayPort,HDMI",На подставку,Наклон,452 х 612 х 185,4.0,165.0,False,...,True,True,True,True,False,False,False,False,False,False
2,24.0,30.0,1.0,"DisplayPort,HDMI,USB Type-B",На подставку,Наклон,NaN,3.5,180.0,False,...,True,True,True,False,False,False,False,False,True,False
3,23.8,30.0,1.0,"HDMI,VGA (D-SUB),DisplayPort","На подставку,Крепление на стену",Наклон,NaN,3.0,100.0,False,...,True,True,True,True,False,False,False,False,False,False
4,27.0,35.0,NaN,"HDMI,VGA (D-SUB)","Крепление на стену,На подставку",NaN,NaN,4.0,75.0,False,...,True,True,True,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3841,27.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,...,NaN,NaN,NaN,False,False,False,False,False,False,True
3842,31.5,30.0,2.0,"HDMI,3.5 мм,VGA (D-SUB)","На подставку,Крепление на стену",NaN,715 x 514 x 248,7.5,75.0,False,...,True,False,False,True,False,False,False,False,False,False
3843,32.0,33.0,1.0,"DisplayPort,HDMI","Крепление на стену,На подставку","Вращение,Регулируемая высота,Наклон",785*120*505,6.6,165.0,True,...,True,True,False,False,False,False,False,False,True,False
3844,23.8,36.0,1.0,"HDMI,DisplayPort,3.5 мм,USB Type-A,VGA (D-SUB)","На подставку,Крепление на стену","Наклон,Поворот,Регулируемая высота",NaN,3.7,75.0,False,...,True,False,False,True,False,False,False,False,False,False
3845,21.5,NaN,2.0,"VGA (D-SUB),HDMI",На подставку,Наклон,489.5 х 391.6 х 183,5.0,60.0,False,...,True,False,False,True,False,False,False,False,False,False

### Преобразуем Углы обзора (Г/В)

In [285]:
df = pd.read_csv('step5_contrast.tsv', sep='\t')

In [286]:
df['Углы обзора (Г/В)'].unique()

array(['178°/178°', nan, '170°/160°', '172°/178°', '178°/170°',
       '170°/170°', '170°/178°', '178°/120°', '90°/65°', '180°/130°',
       '160°/160°', '140°/140°', '176°/176°', '95°/65°', '120°/120°',
       '80°/80°', '180°/100°'], dtype=object)

In [287]:
def parse_viewing_angles(value):
    if pd.isna(value):
        return None, None

    value = value.replace('°', '')
    horizontal, vertical = value.split('/')

    return int(horizontal), int(vertical)

df[['Угол обзора горизонтальный', 'Угол обзора вертикальный']] = df['Углы обзора (Г/В)'].apply(parse_viewing_angles).apply(pd.Series)

df.drop('Углы обзора (Г/В)', axis=1, inplace=True)

df.to_csv('step6_sight_angle.tsv', sep='\t', index=False)

df

,"Диагональ экрана, дюймы","Потребляемая мощность, Вт",Число портов HDMI,Разъёмы монитора,Установка монитора,Регулировки,"Размеры, мм","Вес, кг","Макс. частота обновления, Гц",Изогнутый экран,...,Назначение монитора_Для работы с графикой,Матрица_IPS,Матрица_OLED,Матрица_PLS,Матрица_TFT,Матрица_TN,Матрица_VA,Матрица_nan,Угол обзора горизонтальный,Угол обзора вертикальный
0,34.0,24.0,2.0,"DisplayPort,3.5 мм,HDMI",На подставку,"Вращение,Наклон,Поворот,Регулируемая высота",811/510/210,6.0,180.0,True,...,True,False,False,False,False,False,True,False,178.0,178.0
1,27.0,NaN,1.0,"3.5 мм,DisplayPort,HDMI",На подставку,Наклон,452 х 612 х 185,4.0,165.0,False,...,True,True,False,False,False,False,False,False,178.0,178.0
2,24.0,30.0,1.0,"DisplayPort,HDMI,USB Type-B",На подставку,Наклон,NaN,3.5,180.0,False,...,True,False,False,False,False,False,True,False,178.0,178.0
3,23.8,30.0,1.0,"HDMI,VGA (D-SUB),DisplayPort","На подставку,Крепление на стену",Наклон,NaN,3.0,100.0,False,...,True,True,False,False,False,False,False,False,178.0,178.0
4,27.0,35.0,NaN,"HDMI,VGA (D-SUB)","Крепление на стену,На подставку",NaN,NaN,4.0,75.0,False,...,True,True,False,False,False,False,False,False,178.0,178.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3841,27.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,...,NaN,False,False,False,False,False,False,True,NaN,NaN
3842,31.5,30.0,2.0,"HDMI,3.5 мм,VGA (D-SUB)","На подставку,Крепление на стену",NaN,715 x 514 x 248,7.5,75.0,False,...,False,True,False,False,False,False,False,False,NaN,NaN
3843,32.0,33.0,1.0,"DisplayPort,HDMI","Крепление на стену,На подставку","Вращение,Регулируемая высота,Наклон",785*120*505,6.6,165.0,True,...,False,False,False,False,False,False,True,False,178.0,178.0
3844,23.8,36.0,1.0,"HDMI,DisplayPort,3.5 мм,USB Type-A,VGA (D-SUB)","На подставку,Крепление на стену","Наклон,Поворот,Регулируемая высота",NaN,3.7,75.0,False,...,False,True,False,False,False,False,False,False,NaN,NaN
3845,21.5,NaN,2.0,"VGA (D-SUB),HDMI",На подставку,Наклон,489.5 х 391.6 х 183,5.0,60.0,False,...,False,True,False,False,False,False,False,False,178.0,178.0

### Преобразуем соотношение сторон

In [288]:
df = pd.read_csv('step6_sight_angle.tsv', sep='\t')

In [289]:
df['Соотношение сторон'].unique()

array(['21:9', '16:9', '32:9', '16:10', nan, '5:4', '3:2', '4:3', '1:1'],
      dtype=object)

In [290]:
def aspect_ratio_to_float(ratio):
    if pd.isna(ratio):
        return None
    numerator, denominator = map(int, ratio.split(':'))
    return numerator / denominator

df['Соотношение сторон'] = df['Соотношение сторон'].apply(aspect_ratio_to_float)
df

,"Диагональ экрана, дюймы","Потребляемая мощность, Вт",Число портов HDMI,Разъёмы монитора,Установка монитора,Регулировки,"Размеры, мм","Вес, кг","Макс. частота обновления, Гц",Изогнутый экран,...,Назначение монитора_Для работы с графикой,Матрица_IPS,Матрица_OLED,Матрица_PLS,Матрица_TFT,Матрица_TN,Матрица_VA,Матрица_nan,Угол обзора горизонтальный,Угол обзора вертикальный
0,34.0,24.0,2.0,"DisplayPort,3.5 мм,HDMI",На подставку,"Вращение,Наклон,Поворот,Регулируемая высота",811/510/210,6.0,180.0,True,...,True,False,False,False,False,False,True,False,178.0,178.0
1,27.0,NaN,1.0,"3.5 мм,DisplayPort,HDMI",На подставку,Наклон,452 х 612 х 185,4.0,165.0,False,...,True,True,False,False,False,False,False,False,178.0,178.0
2,24.0,30.0,1.0,"DisplayPort,HDMI,USB Type-B",На подставку,Наклон,NaN,3.5,180.0,False,...,True,False,False,False,False,False,True,False,178.0,178.0
3,23.8,30.0,1.0,"HDMI,VGA (D-SUB),DisplayPort","На подставку,Крепление на стену",Наклон,NaN,3.0,100.0,False,...,True,True,False,False,False,False,False,False,178.0,178.0
4,27.0,35.0,NaN,"HDMI,VGA (D-SUB)","Крепление на стену,На подставку",NaN,NaN,4.0,75.0,False,...,True,True,False,False,False,False,False,False,178.0,178.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3841,27.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,...,NaN,False,False,False,False,False,False,True,NaN,NaN
3842,31.5,30.0,2.0,"HDMI,3.5 мм,VGA (D-SUB)","На подставку,Крепление на стену",NaN,715 x 514 x 248,7.5,75.0,False,...,False,True,False,False,False,False,False,False,NaN,NaN
3843,32.0,33.0,1.0,"DisplayPort,HDMI","Крепление на стену,На подставку","Вращение,Регулируемая высота,Наклон",785*120*505,6.6,165.0,True,...,False,False,False,False,False,False,True,False,178.0,178.0
3844,23.8,36.0,1.0,"HDMI,DisplayPort,3.5 мм,USB Type-A,VGA (D-SUB)","На подставку,Крепление на стену","Наклон,Поворот,Регулируемая высота",NaN,3.7,75.0,False,...,False,True,False,False,False,False,False,False,NaN,NaN
3845,21.5,NaN,2.0,"VGA (D-SUB),HDMI",На подставку,Наклон,489.5 х 391.6 х 183,5.0,60.0,False,...,False,True,False,False,False,False,False,False,178.0,178.0

In [291]:
df.to_csv('step7_ratio.tsv', sep='\t', index=False)

### Преобразуем Покрытие экрана

In [292]:
df = pd.read_csv('step7_ratio.tsv', sep='\t')

In [293]:
df['Покрытие экрана'].unique()

array(['Матовое', nan, 'Глянцевое', 'Антибликовое'], dtype=object)

In [294]:
df_matrix_encoded = pd.get_dummies(df['Покрытие экрана'], prefix='Покрытие', dummy_na=True)

df_final = pd.concat([df, df_matrix_encoded], axis=1)

df_final.drop('Покрытие экрана', axis=1, inplace=True)

df_final.to_csv('step8_cover.tsv', sep='\t', index=False)

df_final

,"Диагональ экрана, дюймы","Потребляемая мощность, Вт",Число портов HDMI,Разъёмы монитора,Установка монитора,Регулировки,"Размеры, мм","Вес, кг","Макс. частота обновления, Гц",Изогнутый экран,...,Матрица_TFT,Матрица_TN,Матрица_VA,Матрица_nan,Угол обзора горизонтальный,Угол обзора вертикальный,Покрытие_Антибликовое,Покрытие_Глянцевое,Покрытие_Матовое,Покрытие_nan
0,34.0,24.0,2.0,"DisplayPort,3.5 мм,HDMI",На подставку,"Вращение,Наклон,Поворот,Регулируемая высота",811/510/210,6.0,180.0,True,...,False,False,True,False,178.0,178.0,False,False,True,False
1,27.0,NaN,1.0,"3.5 мм,DisplayPort,HDMI",На подставку,Наклон,452 х 612 х 185,4.0,165.0,False,...,False,False,False,False,178.0,178.0,False,False,False,True
2,24.0,30.0,1.0,"DisplayPort,HDMI,USB Type-B",На подставку,Наклон,NaN,3.5,180.0,False,...,False,False,True,False,178.0,178.0,False,True,False,False
3,23.8,30.0,1.0,"HDMI,VGA (D-SUB),DisplayPort","На подставку,Крепление на стену",Наклон,NaN,3.0,100.0,False,...,False,False,False,False,178.0,178.0,False,False,True,False
4,27.0,35.0,NaN,"HDMI,VGA (D-SUB)","Крепление на стену,На подставку",NaN,NaN,4.0,75.0,False,...,False,False,False,False,178.0,178.0,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3841,27.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,...,False,False,False,True,NaN,NaN,False,False,False,True
3842,31.5,30.0,2.0,"HDMI,3.5 мм,VGA (D-SUB)","На подставку,Крепление на стену",NaN,715 x 514 x 248,7.5,75.0,False,...,False,False,False,False,NaN,NaN,False,False,True,False
3843,32.0,33.0,1.0,"DisplayPort,HDMI","Крепление на стену,На подставку","Вращение,Регулируемая высота,Наклон",785*120*505,6.6,165.0,True,...,False,False,True,False,178.0,178.0,False,False,True,False
3844,23.8,36.0,1.0,"HDMI,DisplayPort,3.5 мм,USB Type-A,VGA (D-SUB)","На подставку,Крепление на стену","Наклон,Поворот,Регулируемая высота",NaN,3.7,75.0,False,...,False,False,False,False,NaN,NaN,False,False,True,False
3845,21.5,NaN,2.0,"VGA (D-SUB),HDMI",На подставку,Наклон,489.5 х 391.6 х 183,5.0,60.0,False,...,False,False,False,False,178.0,178.0,False,False,True,False

### Преобразуем HDR

In [295]:
df = pd.read_csv('step8_cover.tsv', sep='\t')

In [296]:
df['Технология HDR'].unique()

array([nan, 'Да', 'Нет'], dtype=object)

In [297]:
def is_present(value):
    if pd.isna(value):
        return None

    value = value.strip().lower()
    if 'да' in value:
        return True
    elif 'нет' in value:
        return False
    else:
        return None

df['Технология HDR'] = df['Технология HDR'].apply(is_present)
df

,"Диагональ экрана, дюймы","Потребляемая мощность, Вт",Число портов HDMI,Разъёмы монитора,Установка монитора,Регулировки,"Размеры, мм","Вес, кг","Макс. частота обновления, Гц",Изогнутый экран,...,Матрица_TFT,Матрица_TN,Матрица_VA,Матрица_nan,Угол обзора горизонтальный,Угол обзора вертикальный,Покрытие_Антибликовое,Покрытие_Глянцевое,Покрытие_Матовое,Покрытие_nan
0,34.0,24.0,2.0,"DisplayPort,3.5 мм,HDMI",На подставку,"Вращение,Наклон,Поворот,Регулируемая высота",811/510/210,6.0,180.0,True,...,False,False,True,False,178.0,178.0,False,False,True,False
1,27.0,NaN,1.0,"3.5 мм,DisplayPort,HDMI",На подставку,Наклон,452 х 612 х 185,4.0,165.0,False,...,False,False,False,False,178.0,178.0,False,False,False,True
2,24.0,30.0,1.0,"DisplayPort,HDMI,USB Type-B",На подставку,Наклон,NaN,3.5,180.0,False,...,False,False,True,False,178.0,178.0,False,True,False,False
3,23.8,30.0,1.0,"HDMI,VGA (D-SUB),DisplayPort","На подставку,Крепление на стену",Наклон,NaN,3.0,100.0,False,...,False,False,False,False,178.0,178.0,False,False,True,False
4,27.0,35.0,NaN,"HDMI,VGA (D-SUB)","Крепление на стену,На подставку",NaN,NaN,4.0,75.0,False,...,False,False,False,False,178.0,178.0,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3841,27.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,...,False,False,False,True,NaN,NaN,False,False,False,True
3842,31.5,30.0,2.0,"HDMI,3.5 мм,VGA (D-SUB)","На подставку,Крепление на стену",NaN,715 x 514 x 248,7.5,75.0,False,...,False,False,False,False,NaN,NaN,False,False,True,False
3843,32.0,33.0,1.0,"DisplayPort,HDMI","Крепление на стену,На подставку","Вращение,Регулируемая высота,Наклон",785*120*505,6.6,165.0,True,...,False,False,True,False,178.0,178.0,False,False,True,False
3844,23.8,36.0,1.0,"HDMI,DisplayPort,3.5 мм,USB Type-A,VGA (D-SUB)","На подставку,Крепление на стену","Наклон,Поворот,Регулируемая высота",NaN,3.7,75.0,False,...,False,False,False,False,NaN,NaN,False,False,True,False
3845,21.5,NaN,2.0,"VGA (D-SUB),HDMI",На подставку,Наклон,489.5 х 391.6 х 183,5.0,60.0,False,...,False,False,False,False,178.0,178.0,False,False,True,False

In [298]:
df['Cтандарты HDR'].unique()

array([nan, 'HDR10', 'HDR10+', 'HDR10+,DisplayHDR 400', 'HDR10+,HDR10',
       'DisplayHDR 400', 'DisplayHDR 600', 'DisplayHDR True Black 400',
       'DisplayHDR 400,HDR10', 'HDR10,HDR10+', 'DisplayHDR 1000',
       'DisplayHDR 600,HDR10', 'Dolby Vision',
       'DisplayHDR 400,DisplayHDR 600', 'DisplayHDR 400,HDR10+',
       'DisplayHDR True Black 400,HDR10',
       'HDR10,DisplayHDR True Black 400', 'HDR10,DisplayHDR 400'],
      dtype=object)

In [299]:
hdr_tier = {
    'HDR10': 1,
    'HLG': 2,
    'DisplayHDR 400': 3,
    'DisplayHDR True Black 400': 3,
    'HDR10+': 4,
    'DisplayHDR 600': 5,
    'DisplayHDR 1000': 6,
    'DisplayHDR 1400': 7,
    'Dolby Vision': 8,
    'DisplayHDR 1600': 9,
    'Dolby Vision IQ': 10,
}

def get_max_hdr_tier(hdr_values):
    if pd.isna(hdr_values):
        return None
    hdr_items = hdr_values.split(',')
    hdr_scores = [hdr_tier[item] for item in hdr_items if item in hdr_tier]
    return max(hdr_scores) if hdr_scores else None

df['Cтандарты HDR'] = df['Cтандарты HDR'].apply(get_max_hdr_tier)
df.to_csv('step9_hdr.tsv', sep='\t', index=False)

df

,"Диагональ экрана, дюймы","Потребляемая мощность, Вт",Число портов HDMI,Разъёмы монитора,Установка монитора,Регулировки,"Размеры, мм","Вес, кг","Макс. частота обновления, Гц",Изогнутый экран,...,Матрица_TFT,Матрица_TN,Матрица_VA,Матрица_nan,Угол обзора горизонтальный,Угол обзора вертикальный,Покрытие_Антибликовое,Покрытие_Глянцевое,Покрытие_Матовое,Покрытие_nan
0,34.0,24.0,2.0,"DisplayPort,3.5 мм,HDMI",На подставку,"Вращение,Наклон,Поворот,Регулируемая высота",811/510/210,6.0,180.0,True,...,False,False,True,False,178.0,178.0,False,False,True,False
1,27.0,NaN,1.0,"3.5 мм,DisplayPort,HDMI",На подставку,Наклон,452 х 612 х 185,4.0,165.0,False,...,False,False,False,False,178.0,178.0,False,False,False,True
2,24.0,30.0,1.0,"DisplayPort,HDMI,USB Type-B",На подставку,Наклон,NaN,3.5,180.0,False,...,False,False,True,False,178.0,178.0,False,True,False,False
3,23.8,30.0,1.0,"HDMI,VGA (D-SUB),DisplayPort","На подставку,Крепление на стену",Наклон,NaN,3.0,100.0,False,...,False,False,False,False,178.0,178.0,False,False,True,False
4,27.0,35.0,NaN,"HDMI,VGA (D-SUB)","Крепление на стену,На подставку",NaN,NaN,4.0,75.0,False,...,False,False,False,False,178.0,178.0,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3841,27.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,...,False,False,False,True,NaN,NaN,False,False,False,True
3842,31.5,30.0,2.0,"HDMI,3.5 мм,VGA (D-SUB)","На подставку,Крепление на стену",NaN,715 x 514 x 248,7.5,75.0,False,...,False,False,False,False,NaN,NaN,False,False,True,False
3843,32.0,33.0,1.0,"DisplayPort,HDMI","Крепление на стену,На подставку","Вращение,Регулируемая высота,Наклон",785*120*505,6.6,165.0,True,...,False,False,True,False,178.0,178.0,False,False,True,False
3844,23.8,36.0,1.0,"HDMI,DisplayPort,3.5 мм,USB Type-A,VGA (D-SUB)","На подставку,Крепление на стену","Наклон,Поворот,Регулируемая высота",NaN,3.7,75.0,False,...,False,False,False,False,NaN,NaN,False,False,True,False
3845,21.5,NaN,2.0,"VGA (D-SUB),HDMI",На подставку,Наклон,489.5 х 391.6 х 183,5.0,60.0,False,...,False,False,False,False,178.0,178.0,False,False,True,False

### Преобразуем Разъемы монитора

In [300]:
df = pd.read_csv('step9_hdr.tsv', sep='\t')

In [301]:
df['Разъёмы монитора'].unique()

array(['DisplayPort,3.5 мм,HDMI', '3.5 мм,DisplayPort,HDMI',
       'DisplayPort,HDMI,USB Type-B', 'HDMI,VGA (D-SUB),DisplayPort',
       'HDMI,VGA (D-SUB)', 'HDMI,DisplayPort,USB Type-A',
       'DisplayPort,HDMI,3.5 мм', 'HDMI,USB Type-C', 'HDMI',
       'DisplayPort,HDMI,USB Type-A,USB Type-C',
       'VGA (D-SUB),HDMI,DisplayPort', '3.5 мм,VGA (D-SUB),USB Type-A',
       'HDMI,DisplayPort', 'DisplayPort,HDMI', nan,
       'VGA (D-SUB),HDMI,DisplayPort,DVI', 'DVI,HDMI,VGA (D-SUB)',
       'HDMI,DisplayPort,3.5 мм', 'VGA (D-SUB)',
       'DisplayPort,HDMI,VGA (D-SUB)', 'DisplayPort,HDMI,USB Type-A',
       'HDMI,3.5 мм,DisplayPort', '3.5 мм,HDMI,VGA (D-SUB)',
       'HDMI,3.5 мм,VGA (D-SUB)', 'microHDMI,USB Type-C', '3.5 мм,HDMI',
       'VGA (D-SUB),HDMI', 'MiniHDMI,USB Type-C',
       '3.5 мм,HDMI,DisplayPort', 'HDMI,3.5 мм',
       'DisplayPort,HDMI,VGA (D-SUB),3.5 мм',
       'DisplayPort,HDMI,USB Type-C,USB Type-A,Ethernet',
       'DisplayPort,HDMI,3.5 мм,USB Type-A,USB Type-C,Ethernet',
       'HDMI,USB Type-C,USB Type-A',
       'miniDisplayPort,Thunderbolt,USB Type-A',
       'HDMI,DisplayPort,VGA (D-SUB),3.5 мм',
       'DisplayPort,HDMI,USB Type-A,3.5 мм,Ethernet',
       'USB Type-C,MiniHDMI,3.5 мм',
       '3.5 мм,HDMI,USB Type-A,DisplayPort,USB Type-C',
       'VGA (D-SUB),DisplayPort,HDMI', 'HDMI,DisplayPort,USB Type-C',
       '3.5 мм,USB Type-A,USB Type-B,DisplayPort,HDMI',
       'HDMI,DisplayPort,USB Type-A,USB Type-B,USB Type-C,3.5 мм',
       'DisplayPort,VGA (D-SUB),HDMI',
       'VGA (D-SUB),HDMI,DisplayPort,3.5 мм',
       'MiniHDMI,USB Type-C,3.5 мм', 'HDMI,DisplayPort,VGA (D-SUB)',
       '3.5 мм,DisplayPort,Ethernet,HDMI,USB Type-A,USB Type-B,USB Type-C',
       'USB Type-C', 'HDMI,VGA (D-SUB),3.5 мм',
       'DisplayPort,HDMI,3.5 мм,USB Type-A', 'VGA (D-SUB),HDMI,3.5 мм',
       '3.5 мм,DisplayPort,HDMI,USB Type-A',
       '3.5 мм,DisplayPort,VGA (D-SUB),HDMI', 'USB Type-C,MiniHDMI',
       'HDMI,DisplayPort,3.5 мм,USB Type-C', 'HDMI,USB Type-A,USB Type-C',
       'DisplayPort,HDMI,USB Type-C', 'MiniHDMI,Thunderbolt,USB Type-C',
       'HDMI,VGA (D-SUB),3.5 мм,DisplayPort',
       'HDMI,DisplayPort,USB Type-A,USB Type-B,USB Type-C,3.5 мм,Ethernet',
       'HDMI,VGA (D-SUB),DisplayPort,USB Type-A,3.5 мм',
       'HDMI,3.5 мм,Ethernet', 'DisplayPort,VGA (D-SUB)',
       '3.5 мм,DisplayPort,HDMI,USB Type-B',
       'DisplayPort,HDMI,USB Type-A,3.5 мм',
       '3.5 мм,DisplayPort,HDMI,USB Type-C', 'HDMI,USB Type-A',
       '3.5 мм,HDMI,USB Type-C', '3.5 мм,MiniHDMI,USB Type-C',
       'USB Type-C,DisplayPort,HDMI',
       'HDMI,USB Type-A,DisplayPort,3.5 мм',
       'HDMI,DisplayPort,USB Type-A,3.5 мм',
       'DVI,HDMI,DisplayPort,VGA (D-SUB)', 'DVI,VGA (D-SUB)',
       'DisplayPort,HDMI,USB Type-B,3.5 мм',
       'HDMI,3.5 мм,USB Type-C,DisplayPort',
       '3.5 мм,VGA (D-SUB),DisplayPort,HDMI', 'USB Type-C,HDMI',
       'HDMI,USB Type-C,USB Type-A,USB Type-B,DisplayPort,3.5 мм',
       'VGA (D-SUB),DVI,DisplayPort,HDMI,USB Type-B,USB Type-A,3.5 мм',
       '3.5 мм,HDMI,DisplayPort,USB Type-C,USB Type-B,USB Type-A',
       '3.5 мм,USB Type-A,USB Type-C,DisplayPort,HDMI',
       'HDMI,3.5 мм,DisplayPort,VGA (D-SUB)',
       'HDMI,USB Type-A,DisplayPort', '3.5 мм,HDMI,USB Type-A,USB Type-C',
       'HDMI,USB Type-C,3.5 мм,DisplayPort',
       'VGA (D-SUB),HDMI,DisplayPort,AV',
       'HDMI,3.5 мм,DisplayPort,USB Type-A', 'DisplayPort',
       'VGA (D-SUB),DVI', 'HDMI,DisplayPort,AV',
       'HDMI,VGA (D-SUB),3.5 мм,USB Type-A',
       'HDMI,USB Type-A,3.5 мм,DisplayPort,USB Type-C',
       '3.5 мм,DisplayPort,HDMI,VGA (D-SUB)',
       'HDMI,DisplayPort,USB Type-B', 'MiniHDMI,3.5 мм,USB Type-C',
       'HDMI,DisplayPort,USB Type-C,AV', 'VGA (D-SUB),HDMI,AV',
       'DisplayPort,HDMI,USB Type-A,USB Type-B',
       'USB Type-A,HDMI,DisplayPort',
       'DisplayPort,HDMI,3.5 мм,USB Type-A,Thunderbolt',
       '3.5 мм,MiniHDMI,Thunderbolt', 'MiniHDMI',
       'HDMI,USB Type-C,USB Type-A,DisplayPort,3.5 мм',
       '3.5 мм,DisplayPort,HDMI,USB Type-A,USB Type-B', 'DVI',
       'USB Type-C,3.5 мм,MiniHDMI', 'USB Type-A,HDMI',
       '3.5 мм,HDMI,USB Type-A,USB Type-B,USB Type-C',
       'HDMI,DisplayPort,DVI', 'HDMI,USB Type-C,AV',
       'HDMI,DisplayPort,USB Type-A,USB Type-C,Thunderbolt',
       'HDMI,DVI,VGA (D-SUB)', 'HDMI,USB Type-C,DisplayPort',
       'DVI,HDMI,DisplayPort,AV', 'HDMI,DisplayPort,USB Type-C,3.5 мм',
       'HDMI,miniDisplayPort,USB Type-C,USB Type-A,3.5 мм',
       'HDMI,DVI,DisplayPort,3.5 мм',
       'USB Type-C,miniDisplayPort,microHDMI', 'HDMI,3.5 мм,USB Type-A',
       'HDMI,VGA (D-SUB),DVI', 'DisplayPort,USB Type-A,HDMI,USB Type-B',
       'USB Type-A,3.5 мм,DisplayPort,HDMI',
       'DisplayPort,HDMI,USB Type-C,USB Type-A,3.5 мм',
       'USB Type-B,USB Type-C,HDMI,DisplayPort,3.5 мм',
       'Thunderbolt,HDMI',
       'HDMI,VGA (D-SUB),3.5 мм,DisplayPort,USB Type-A',
       '3.5 мм,DisplayPort,HDMI,VGA (D-SUB),USB Type-C',
       'HDMI,DisplayPort,USB Type-C,USB Type-A',
       'DisplayPort,HDMI,USB Type-A,USB Type-B,USB Type-C,3.5 мм',
       'DVI,3.5 мм,DisplayPort,HDMI', 'VGA (D-SUB),HDMI,USB Type-C',
       'DisplayPort,3.5 мм,USB Type-C', '3.5 мм,HDMI,AV',
       'DisplayPort,HDMI,3.5 мм,DVI',
       'DVI,HDMI,DisplayPort,miniDisplayPort', '3.5 мм,DVI,HDMI',
       '3.5 мм,DisplayPort,microHDMI,USB Type-C', 'USB Type-B,microHDMI',
       '3.5 мм,USB Type-C', 'HDMI,VGA (D-SUB),USB Type-A',
       'DisplayPort,HDMI,USB Type-C,3.5 мм',
       '3.5 мм,DisplayPort,HDMI,USB Type-A,USB Type-C,USB Type-B',
       '3.5 мм,HDMI,DisplayPort,USB Type-A,USB Type-C',
       'HDMI,3.5 мм,DisplayPort,USB Type-A,USB Type-B,VGA (D-SUB)',
       'HDMI,DisplayPort,3.5 мм,USB Type-C,USB Type-A,USB Type-B',
       'DVI,HDMI', '3.5 мм,HDMI,USB Type-A,VGA (D-SUB)',
       'VGA (D-SUB),HDMI,DisplayPort,USB Type-C',
       'DisplayPort,USB Type-A,HDMI',
       'HDMI,DisplayPort,3.5 мм,USB Type-A', 'DisplayPort,DVI,HDMI',
       'USB Type-C,Thunderbolt,HDMI',
       'HDMI,3.5 мм,DisplayPort,USB Type-A,USB Type-C',
       'DisplayPort,HDMI,USB Type-C,3.5 мм,USB Type-A,USB Type-B',
       'DisplayPort,USB Type-A,USB Type-C,HDMI', 'DisplayPort,HDMI,DVI',
       '3.5 мм,DisplayPort,HDMI,USB Type-C,USB Type-A',
       'USB Type-C,HDMI,DisplayPort,3.5 мм',
       'DisplayPort,HDMI,3.5 мм,USB Type-C',
       'USB Type-C,HDMI,DisplayPort', '3.5 мм,AV,HDMI,VGA (D-SUB)',
       'DisplayPort,HDMI,VGA (D-SUB),USB Type-A,3.5 мм',
       'HDMI,DisplayPort,USB Type-A,USB Type-B,3.5 мм',
       'HDMI,USB Type-A,USB Type-B,VGA (D-SUB)', 'Thunderbolt,USB Type-C',
       'HDMI,DisplayPort,3.5 мм,USB Type-A,VGA (D-SUB)',
       'HDMI,3.5 мм,USB Type-C', 'USB Type-A,USB Type-C,HDMI',
       'DVI,HDMI,VGA (D-SUB),3.5 мм',
       'DisplayPort,3.5 мм,HDMI,USB Type-A', '3.5 мм,USB Type-C,HDMI',
       '3.5 мм,HDMI,DisplayPort,VGA (D-SUB)',
       'microHDMI,USB Type-C,3.5 мм',
       'HDMI,VGA (D-SUB),DisplayPort,USB Type-A',
       'HDMI,VGA (D-SUB),DisplayPort,3.5 мм',
       'HDMI,USB Type-A,DisplayPort,VGA (D-SUB)',
       'VGA (D-SUB),HDMI,USB Type-A',
       '3.5 мм,DisplayPort,HDMI,USB Type-A,USB Type-C,Ethernet',
       'HDMI,VGA (D-SUB),DisplayPort,USB Type-B',
       'HDMI,DisplayPort,USB Type-B,3.5 мм',
       'HDMI,USB Type-A,USB Type-C,DisplayPort',
       '3.5 мм,HDMI,USB Type-A,DisplayPort',
       '3.5 мм,DVI,HDMI,VGA (D-SUB)',
       'DisplayPort,3.5 мм,HDMI,USB Type-A,USB Type-C',
       'HDMI,USB Type-A,3.5 мм,VGA (D-SUB),USB Type-C,DisplayPort',
       '3.5 мм,DisplayPort,USB Type-A,HDMI', 'HDMI,USB Type-A,3.5 мм',
       'HDMI,DisplayPort,3.5 мм,USB Type-A,USB Type-C',
       'HDMI,VGA (D-SUB),USB Type-C',
       'HDMI,DisplayPort,USB Type-A,USB Type-C,3.5 мм',
       'HDMI,DisplayPort,DVI,3.5 мм',
       '3.5 мм,HDMI,USB Type-C,miniDisplayPort',
       'HDMI,DisplayPort,3.5 мм,USB Type-B,USB Type-C',
       'USB Type-A,HDMI,3.5 мм,DisplayPort', 'DVI,HDMI,DisplayPort',
       '3.5 мм,DisplayPort,HDMI,USB Type-A,VGA (D-SUB)',
       '3.5 мм,HDMI,USB Type-A', '3.5 мм,HDMI,DisplayPort,USB Type-A',
       'DisplayPort,HDMI,3.5 мм,USB Type-C,USB Type-A,Ethernet',
       'HDMI,DisplayPort,Thunderbolt',
       '3.5 мм,MiniHDMI,USB Type-C,USB Type-A', 'microHDMI',
       'HDMI,USB Type-A,USB Type-C,VGA (D-SUB)',
       'HDMI,DisplayPort,3.5 мм,USB Type-B,USB Type-A,USB Type-C',
       '3.5 мм,USB Type-C,MiniHDMI',
       'HDMI,DisplayPort,USB Type-C,Thunderbolt,AV',
       'DVI,VGA (D-SUB),USB Type-B', '3.5 мм,HDMI,Thunderbolt,USB Type-C',
       'miniDisplayPort,Thunderbolt',
       'Thunderbolt,DisplayPort,HDMI,VGA (D-SUB)',
       'HDMI,DVI,USB Type-C,USB Type-A',
       '3.5 мм,USB Type-B,DisplayPort,HDMI,VGA (D-SUB)',
       'HDMI,DisplayPort,USB Type-C,Ethernet,USB Type-A',
       'Thunderbolt,HDMI,3.5 мм', 'HDMI,3.5 мм,USB Type-A,DisplayPort',
       'Ethernet,DisplayPort,HDMI,USB Type-A,USB Type-C',
       'VGA (D-SUB),HDMI,DVI,3.5 мм', 'Ethernet,DisplayPort,HDMI,3.5 мм',
       'VGA (D-SUB),DVI,HDMI', 'AV,HDMI,USB Type-A,VGA (D-SUB)',
       'DisplayPort,HDMI,Ethernet,USB Type-A,USB Type-C',
       '3.5 мм,USB Type-C,miniDisplayPort,HDMI',
       '3.5 мм,DVI,DisplayPort,HDMI,USB Type-A,VGA (D-SUB)',
       'USB Type-A,DisplayPort,HDMI,3.5 мм', 'HDMI,DVI,DisplayPort',
       'HDMI,3.5 мм,Thunderbolt,USB Type-C',
       'USB Type-C,DisplayPort,Ethernet,HDMI,USB Type-A',
       'VGA (D-SUB),DVI,DisplayPort,HDMI,3.5 мм',
       'USB Type-C,HDMI,DisplayPort,USB Type-A,3.5 мм',
       'DisplayPort,USB Type-A,HDMI,Ethernet', 'Ethernet,HDMI',
       'HDMI,3.5 мм,DisplayPort,USB Type-C,Ethernet',
       '3.5 мм,HDMI,USB Type-C,DisplayPort',
       '3.5 мм,DisplayPort,USB Type-A',
       'USB Type-C,HDMI,Ethernet,DisplayPort,USB Type-A'], dtype=object)

In [302]:
df['Разъёмы монитора'] = df['Разъёмы монитора'].str.split(',')
df_exploded = df.explode('Разъёмы монитора')
df_encoded = pd.get_dummies(df_exploded, columns=['Разъёмы монитора'])

aggregation_dict = {}
for col in df_encoded.columns:
    if 'Разъёмы монитора' in col:
        aggregation_dict[col] = 'max'
    else:
        aggregation_dict[col] = 'first'

df_final = df_encoded.groupby(level=0).agg(aggregation_dict)

df_final.to_csv('step10_ports.tsv', sep='\t', index=False)

df_final

,"Диагональ экрана, дюймы","Потребляемая мощность, Вт",Число портов HDMI,Установка монитора,Регулировки,"Размеры, мм","Вес, кг","Макс. частота обновления, Гц",Изогнутый экран,Контрастность,...,Разъёмы монитора_Ethernet,Разъёмы монитора_HDMI,Разъёмы монитора_MiniHDMI,Разъёмы монитора_Thunderbolt,Разъёмы монитора_USB Type-A,Разъёмы монитора_USB Type-B,Разъёмы монитора_USB Type-C,Разъёмы монитора_VGA (D-SUB),Разъёмы монитора_microHDMI,Разъёмы монитора_miniDisplayPort
0,34.0,24.0,2.0,На подставку,"Вращение,Наклон,Поворот,Регулируемая высота",811/510/210,6.0,180.0,True,3000.0,...,False,True,False,False,False,False,False,False,False,False
1,27.0,NaN,1.0,На подставку,Наклон,452 х 612 х 185,4.0,165.0,False,10001.0,...,False,True,False,False,False,False,False,False,False,False
2,24.0,30.0,1.0,На подставку,Наклон,None,3.5,180.0,False,10000.0,...,False,True,False,False,False,True,False,False,False,False
3,23.8,30.0,1.0,"На подставку,Крепление на стену",Наклон,None,3.0,100.0,False,1100.0,...,False,True,False,False,False,False,False,True,False,False
4,27.0,35.0,NaN,"Крепление на стену,На подставку",None,None,4.0,75.0,False,NaN,...,False,True,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3841,27.0,NaN,NaN,None,None,None,NaN,NaN,False,NaN,...,False,False,False,False,False,False,False,False,False,False
3842,31.5,30.0,2.0,"На подставку,Крепление на стену",None,715 x 514 x 248,7.5,75.0,False,3000.0,...,False,True,False,False,False,False,False,True,False,False
3843,32.0,33.0,1.0,"Крепление на стену,На подставку","Вращение,Регулируемая высота,Наклон",785*120*505,6.6,165.0,True,3000.0,...,False,True,False,False,False,False,False,False,False,False
3844,23.8,36.0,1.0,"На подставку,Крепление на стену","Наклон,Поворот,Регулируемая высота",None,3.7,75.0,False,1000.0,...,False,True,False,False,True,False,False,True,False,False
3845,21.5,NaN,2.0,На подставку,Наклон,489.5 х 391.6 х 183,5.0,60.0,False,1000.0,...,False,True,False,False,False,False,False,True,False,False

### Преобразуем Установка монитора

In [303]:
df = pd.read_csv('step10_ports.tsv', sep='\t')

In [304]:
df['Установка монитора'].unique()

array(['На подставку', 'На подставку,Крепление на стену',
       'Крепление на стену,На подставку', nan, 'Крепление на стену'],
      dtype=object)

In [305]:
df['Установка монитора'] = df['Установка монитора'].str.split(',')
df_exploded = df.explode('Установка монитора')
df_encoded = pd.get_dummies(df_exploded, columns=['Установка монитора'])

aggregation_dict = {}
for col in df_encoded.columns:
    if 'Установка монитора' in col:
        aggregation_dict[col] = 'max'
    else:
        aggregation_dict[col] = 'first'

df_final = df_encoded.groupby(level=0).agg(aggregation_dict)

df_final.to_csv('step11_placement.tsv', sep='\t', index=False)

df_final

,"Диагональ экрана, дюймы","Потребляемая мощность, Вт",Число портов HDMI,Регулировки,"Размеры, мм","Вес, кг","Макс. частота обновления, Гц",Изогнутый экран,Контрастность,Соотношение сторон,...,Разъёмы монитора_MiniHDMI,Разъёмы монитора_Thunderbolt,Разъёмы монитора_USB Type-A,Разъёмы монитора_USB Type-B,Разъёмы монитора_USB Type-C,Разъёмы монитора_VGA (D-SUB),Разъёмы монитора_microHDMI,Разъёмы монитора_miniDisplayPort,Установка монитора_Крепление на стену,Установка монитора_На подставку
0,34.0,24.0,2.0,"Вращение,Наклон,Поворот,Регулируемая высота",811/510/210,6.0,180.0,True,3000.0,2.333333,...,False,False,False,False,False,False,False,False,False,True
1,27.0,NaN,1.0,Наклон,452 х 612 х 185,4.0,165.0,False,10001.0,1.777778,...,False,False,False,False,False,False,False,False,False,True
2,24.0,30.0,1.0,Наклон,None,3.5,180.0,False,10000.0,1.777778,...,False,False,False,True,False,False,False,False,False,True
3,23.8,30.0,1.0,Наклон,None,3.0,100.0,False,1100.0,1.777778,...,False,False,False,False,False,True,False,False,True,True
4,27.0,35.0,NaN,None,None,4.0,75.0,False,NaN,1.777778,...,False,False,False,False,False,True,False,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3841,27.0,NaN,NaN,None,None,NaN,NaN,False,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
3842,31.5,30.0,2.0,None,715 x 514 x 248,7.5,75.0,False,3000.0,1.777778,...,False,False,False,False,False,True,False,False,True,True
3843,32.0,33.0,1.0,"Вращение,Регулируемая высота,Наклон",785*120*505,6.6,165.0,True,3000.0,1.777778,...,False,False,False,False,False,False,False,False,True,True
3844,23.8,36.0,1.0,"Наклон,Поворот,Регулируемая высота",None,3.7,75.0,False,1000.0,1.777778,...,False,False,True,False,False,True,False,False,True,True
3845,21.5,NaN,2.0,Наклон,489.5 х 391.6 х 183,5.0,60.0,False,1000.0,1.777778,...,False,False,False,False,False,True,False,False,False,True

### Преобразуем Регулировки

In [306]:
df = pd.read_csv('step11_placement.tsv', sep='\t')

In [307]:
df['Регулировки'].unique()

array(['Вращение,Наклон,Поворот,Регулируемая высота', 'Наклон', nan,
       'Вращение', 'Наклон,Поворот', 'Регулируемая высота',
       'Поворот,Регулируемая высота,Наклон,Вращение',
       'Поворот,Регулируемая высота,Наклон',
       'Наклон,Поворот,Регулируемая высота',
       'Наклон,Поворот,Регулируемая высота,Вращение',
       'Регулируемая высота,Наклон,Поворот', 'Регулируемая высота,Наклон',
       'Регулируемая высота,Поворот,Вращение,Наклон',
       'Наклон,Регулируемая высота,Поворот,Вращение',
       'Наклон,Вращение,Поворот', 'Поворот',
       'Наклон,Вращение,Поворот,Регулируемая высота',
       'Наклон,Регулируемая высота',
       'Вращение,Поворот,Регулируемая высота', 'Поворот,Вращение,Наклон',
       'Вращение,Наклон,Регулируемая высота',
       'Поворот,Регулируемая высота', 'Поворот,Вращение',
       'Поворот,Наклон,Регулируемая высота,Вращение',
       'Регулируемая высота,Поворот',
       'Вращение,Наклон,Регулируемая высота,Поворот',
       'Наклон,Регулируемая высота,Поворот',
       'Наклон,Вращение,Регулируемая высота',
       'Регулируемая высота,Наклон,Поворот,Вращение', 'Вращение,Наклон',
       'Регулируемая высота,Поворот,Наклон', 'Вращение,Наклон,Поворот',
       'Поворот,Наклон,Регулируемая высота',
       'Вращение,Регулируемая высота,Поворот,Наклон',
       'Регулируемая высота,Наклон,Вращение', 'Поворот,Наклон',
       'Наклон,Вращение', 'Вращение,Регулируемая высота',
       'Поворот,Регулируемая высота,Вращение,Наклон',
       'Наклон,Регулируемая высота,Вращение',
       'Вращение,Регулируемая высота,Наклон',
       'Регулируемая высота,Наклон,Вращение,Поворот',
       'Поворот,Наклон,Вращение,Регулируемая высота',
       'Вращение,Поворот,Наклон,Регулируемая высота',
       'Регулируемая высота,Вращение,Поворот,Наклон',
       'Вращение,Регулируемая высота,Наклон,Поворот',
       'Наклон,Поворот,Вращение', 'Вращение,Поворот,Наклон',
       'Регулируемая высота,Поворот,Наклон,Вращение',
       'Регулируемая высота,Вращение,Наклон',
       'Регулируемая высота,Вращение',
       'Наклон,Поворот,Вращение,Регулируемая высота'], dtype=object)

In [308]:
df['Регулировки'] = df['Регулировки'].str.split(',')
df_exploded = df.explode('Регулировки')
df_encoded = pd.get_dummies(df_exploded, columns=['Регулировки'])

aggregation_dict = {}
for col in df_encoded.columns:
    if 'Регулировки' in col:
        aggregation_dict[col] = 'max'
    else:
        aggregation_dict[col] = 'first'

df_final = df_encoded.groupby(level=0).agg(aggregation_dict)

df_final.to_csv('step12_movement.tsv', sep='\t', index=False)

df_final

,"Диагональ экрана, дюймы","Потребляемая мощность, Вт",Число портов HDMI,"Размеры, мм","Вес, кг","Макс. частота обновления, Гц",Изогнутый экран,Контрастность,Соотношение сторон,"Время отклика, мс",...,Разъёмы монитора_USB Type-C,Разъёмы монитора_VGA (D-SUB),Разъёмы монитора_microHDMI,Разъёмы монитора_miniDisplayPort,Установка монитора_Крепление на стену,Установка монитора_На подставку,Регулировки_Вращение,Регулировки_Наклон,Регулировки_Поворот,Регулировки_Регулируемая высота
0,34.0,24.0,2.0,811/510/210,6.0,180.0,True,3000.0,2.333333,1.0,...,False,False,False,False,False,True,True,True,True,True
1,27.0,NaN,1.0,452 х 612 х 185,4.0,165.0,False,10001.0,1.777778,1.0,...,False,False,False,False,False,True,False,True,False,False
2,24.0,30.0,1.0,None,3.5,180.0,False,10000.0,1.777778,1.0,...,False,False,False,False,False,True,False,True,False,False
3,23.8,30.0,1.0,None,3.0,100.0,False,1100.0,1.777778,1.0,...,False,True,False,False,True,True,False,True,False,False
4,27.0,35.0,NaN,None,4.0,75.0,False,NaN,1.777778,8.0,...,False,True,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3841,27.0,NaN,NaN,None,NaN,NaN,False,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
3842,31.5,30.0,2.0,715 x 514 x 248,7.5,75.0,False,3000.0,1.777778,4.0,...,False,True,False,False,True,True,False,False,False,False
3843,32.0,33.0,1.0,785*120*505,6.6,165.0,True,3000.0,1.777778,2.0,...,False,False,False,False,True,True,True,True,False,True
3844,23.8,36.0,1.0,None,3.7,75.0,False,1000.0,1.777778,5.0,...,False,True,False,False,True,True,False,True,True,True
3845,21.5,NaN,2.0,489.5 х 391.6 х 183,5.0,60.0,False,1000.0,1.777778,5.0,...,False,True,False,False,False,True,False,True,False,False

### Преобразуем Размеры

In [309]:
df = pd.read_csv('step12_movement.tsv', sep='\t')

In [310]:
df['Размеры, мм'].unique()

array(['811/510/210', '452 х 612 х 185', nan, ..., '685*130*442',
       '615x466x291', '489.5 х 391.6 х 183'], dtype=object)

In [311]:
df.drop('Цвет', axis=1, inplace=True)
df.drop('Частота горизонтальной развертки, кГц', axis=1, inplace=True)
df.drop('Частота вертикальной развертки, Гц', axis=1, inplace=True)
df.drop('Стандарт крепления VESA', axis=1, inplace=True)
df.drop('Уровни регулировки подставки', axis=1, inplace=True)

In [312]:
def clean_and_split_dimensions(dimensions):
    if pd.isna(dimensions):
        return [None, None, None]

    matches = re.findall(r'\d+\.?\d*', dimensions)

    numbers = [float(num) for num in matches[:3]]

    while len(numbers) < 3:
        numbers.append(None)
    
    return numbers

df[['Ширина, мм', 'Высота, мм', 'Глубина, мм']] = pd.DataFrame(df['Размеры, мм'].apply(clean_and_split_dimensions).to_list(), index=df.index)
df.drop('Размеры, мм', axis=1, inplace=True)

df.to_csv('step13_dimensions.tsv', sep='\t', index=False)

df

,"Диагональ экрана, дюймы","Потребляемая мощность, Вт",Число портов HDMI,"Вес, кг","Макс. частота обновления, Гц",Изогнутый экран,Контрастность,Соотношение сторон,"Время отклика, мс",Web-камера,...,Разъёмы монитора_miniDisplayPort,Установка монитора_Крепление на стену,Установка монитора_На подставку,Регулировки_Вращение,Регулировки_Наклон,Регулировки_Поворот,Регулировки_Регулируемая высота,"Ширина, мм","Высота, мм","Глубина, мм"
0,34.0,24.0,2.0,6.0,180.0,True,3000.0,2.333333,1.0,False,...,False,False,True,True,True,True,True,811.0,510.0,210.0
1,27.0,NaN,1.0,4.0,165.0,False,10001.0,1.777778,1.0,False,...,False,False,True,False,True,False,False,452.0,612.0,185.0
2,24.0,30.0,1.0,3.5,180.0,False,10000.0,1.777778,1.0,False,...,False,False,True,False,True,False,False,NaN,NaN,NaN
3,23.8,30.0,1.0,3.0,100.0,False,1100.0,1.777778,1.0,False,...,False,True,True,False,True,False,False,NaN,NaN,NaN
4,27.0,35.0,NaN,4.0,75.0,False,NaN,1.777778,8.0,False,...,False,True,True,False,False,False,False,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3841,27.0,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,False,...,False,False,False,False,False,False,False,NaN,NaN,NaN
3842,31.5,30.0,2.0,7.5,75.0,False,3000.0,1.777778,4.0,False,...,False,True,True,False,False,False,False,715.0,514.0,248.0
3843,32.0,33.0,1.0,6.6,165.0,True,3000.0,1.777778,2.0,False,...,False,True,True,True,True,False,True,785.0,120.0,505.0
3844,23.8,36.0,1.0,3.7,75.0,False,1000.0,1.777778,5.0,True,...,False,True,True,False,True,True,True,NaN,NaN,NaN
3845,21.5,NaN,2.0,5.0,60.0,False,1000.0,1.777778,5.0,False,...,False,False,True,False,True,False,False,489.5,391.6,183.0

### Преобразуем Бренд

In [313]:
df = pd.read_csv('step13_dimensions.tsv', sep='\t')

In [314]:
df['Бренд'].unique()

array(['Xiaomi', nan, 'Samsung', 'Digma', 'Compit', 'SANC', 'Hartens',
       'AOC', 'MSI', 'Redmi', 'Ninkear', 'TUOSHUO', 'LG', 'ASUS',
       'Gigabyte', 'Hisense', 'Lime', 'Dell', 'Acer', 'BenQ',
       'ThundeRobot', 'MAIBENBEN', 'Lenovo', 'Digma Pro', 'HP', 'Philips',
       'Raskat', 'IRBIS', 'Hikvision', 'AIWA', 'Dahua', 'HIPER', 'HUAWEI',
       'Apple', 'TCL', 'ASRock', 'Razer', 'HyperX'], dtype=object)

In [315]:
brand_counts = df['Бренд'].value_counts()

frequency_df = pd.DataFrame(brand_counts).reset_index()
frequency_df.columns = ['Бренд', 'Частота']

frequency_df = frequency_df.sort_values(by='Частота')

brand_mapping = {brand: idx + 1 for idx, brand in enumerate(frequency_df['Бренд'])}

brand_mapping[None] = 0

df['Бренд'] = df['Бренд'].map(brand_mapping).fillna(0)

df['Бренд'] = df['Бренд'].astype(int)

df.to_csv('step14_brand.tsv', sep='\t', index=False)

df

,"Диагональ экрана, дюймы","Потребляемая мощность, Вт",Число портов HDMI,"Вес, кг","Макс. частота обновления, Гц",Изогнутый экран,Контрастность,Соотношение сторон,"Время отклика, мс",Web-камера,...,Разъёмы монитора_miniDisplayPort,Установка монитора_Крепление на стену,Установка монитора_На подставку,Регулировки_Вращение,Регулировки_Наклон,Регулировки_Поворот,Регулировки_Регулируемая высота,"Ширина, мм","Высота, мм","Глубина, мм"
0,34.0,24.0,2.0,6.0,180.0,True,3000.0,2.333333,1.0,False,...,False,False,True,True,True,True,True,811.0,510.0,210.0
1,27.0,NaN,1.0,4.0,165.0,False,10001.0,1.777778,1.0,False,...,False,False,True,False,True,False,False,452.0,612.0,185.0
2,24.0,30.0,1.0,3.5,180.0,False,10000.0,1.777778,1.0,False,...,False,False,True,False,True,False,False,NaN,NaN,NaN
3,23.8,30.0,1.0,3.0,100.0,False,1100.0,1.777778,1.0,False,...,False,True,True,False,True,False,False,NaN,NaN,NaN
4,27.0,35.0,NaN,4.0,75.0,False,NaN,1.777778,8.0,False,...,False,True,True,False,False,False,False,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3841,27.0,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,False,...,False,False,False,False,False,False,False,NaN,NaN,NaN
3842,31.5,30.0,2.0,7.5,75.0,False,3000.0,1.777778,4.0,False,...,False,True,True,False,False,False,False,715.0,514.0,248.0
3843,32.0,33.0,1.0,6.6,165.0,True,3000.0,1.777778,2.0,False,...,False,True,True,True,True,False,True,785.0,120.0,505.0
3844,23.8,36.0,1.0,3.7,75.0,False,1000.0,1.777778,5.0,True,...,False,True,True,False,True,True,True,NaN,NaN,NaN
3845,21.5,NaN,2.0,5.0,60.0,False,1000.0,1.777778,5.0,False,...,False,False,True,False,True,False,False,489.5,391.6,183.0

### Преобразуем страну

In [316]:
df = pd.read_csv('step14_brand.tsv', sep='\t')

In [317]:
df['Страна-изготовитель'].unique()

array(['Китай', 'Беларусь', nan, 'Вьетнам', 'Китай (Тайвань)', 'Россия',
       'Не указана', 'Таиланд', 'Египет', 'Корея', 'Китай (Гонконг)',
       'США', 'Китай,Малайзия,Вьетнам', 'Китай,Австралия', 'Япония'],
      dtype=object)

In [318]:
df['Страна-изготовитель'] = df['Страна-изготовитель'].replace('Не указана', None)

def split_countries(value):
    if pd.isna(value):
        return []
    return [country.strip() for country in value.split(',')]

df['Страна-изготовитель'] = df['Страна-изготовитель'].replace(
    {'Китай (Тайвань)': 'Китай', 'Китай (Гонконг)': 'Китай'}
)

df['Страна-изготовитель_Все'] = df['Страна-изготовитель'].apply(split_countries)

all_countries = df['Страна-изготовитель_Все'].explode()
country_freq = all_countries.value_counts()
country_mapping = {country: i+1 for i, country in enumerate(country_freq.index[::-1])}

def map_country_list(country_list):
    if not country_list:
        return 0
    return max([country_mapping.get(country, 0) for country in country_list])

df['Страна-изготовитель'] = df['Страна-изготовитель_Все'].apply(map_country_list)

df.drop(columns=['Страна-изготовитель_Все'], inplace=True)

df.to_csv('step15_country.tsv', sep='\t', index=False)

df

,"Диагональ экрана, дюймы","Потребляемая мощность, Вт",Число портов HDMI,"Вес, кг","Макс. частота обновления, Гц",Изогнутый экран,Контрастность,Соотношение сторон,"Время отклика, мс",Web-камера,...,Разъёмы монитора_miniDisplayPort,Установка монитора_Крепление на стену,Установка монитора_На подставку,Регулировки_Вращение,Регулировки_Наклон,Регулировки_Поворот,Регулировки_Регулируемая высота,"Ширина, мм","Высота, мм","Глубина, мм"
0,34.0,24.0,2.0,6.0,180.0,True,3000.0,2.333333,1.0,False,...,False,False,True,True,True,True,True,811.0,510.0,210.0
1,27.0,NaN,1.0,4.0,165.0,False,10001.0,1.777778,1.0,False,...,False,False,True,False,True,False,False,452.0,612.0,185.0
2,24.0,30.0,1.0,3.5,180.0,False,10000.0,1.777778,1.0,False,...,False,False,True,False,True,False,False,NaN,NaN,NaN
3,23.8,30.0,1.0,3.0,100.0,False,1100.0,1.777778,1.0,False,...,False,True,True,False,True,False,False,NaN,NaN,NaN
4,27.0,35.0,NaN,4.0,75.0,False,NaN,1.777778,8.0,False,...,False,True,True,False,False,False,False,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3841,27.0,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,False,...,False,False,False,False,False,False,False,NaN,NaN,NaN
3842,31.5,30.0,2.0,7.5,75.0,False,3000.0,1.777778,4.0,False,...,False,True,True,False,False,False,False,715.0,514.0,248.0
3843,32.0,33.0,1.0,6.6,165.0,True,3000.0,1.777778,2.0,False,...,False,True,True,True,True,False,True,785.0,120.0,505.0
3844,23.8,36.0,1.0,3.7,75.0,False,1000.0,1.777778,5.0,True,...,False,True,True,False,True,True,True,NaN,NaN,NaN
3845,21.5,NaN,2.0,5.0,60.0,False,1000.0,1.777778,5.0,False,...,False,False,True,False,True,False,False,489.5,391.6,183.0

### Преобразуем Гарантийный срок

In [319]:
df = pd.read_csv('step15_country.tsv', sep='\t')

In [320]:
df['Гарантийный срок'].unique()

array(['1 год', '1', '12', '12 месяцев', '365 дней', '13',
       '3 года гарантия от производителя', nan, '6 месяцев', '36 месяцев',
       '3 год', '1 месяц', '3 года', '1 год гарантия производителя',
       '3 мес.', 'один год', '36', '1 года', '12мес', '1 year', '24 мес.',
       '365', '12 мес.', '30 дней', 'OдNH Год', '14 дней',
       'официальная гарантия производителя', '3',
       'см. в каталоге товаров', '3 года от производителя', '3 месяца',
       '3 мес', '24', '36 мес.', '24 месяца', '12 мес', '6 мес', '2 года',
       '1Год', '36day', '24 мес', '1месяц', '6мес',
       'Гарантия от производителя', '36 мес', '6 месяцев.', '6',
       '0.083333333333333', '30', 'Официальная гарантия производителя',
       'три года', 'Срок гарантии 3 года',
       'официальная от LG по гарантийному талону', '1年', '2',
       'Срок гарантии 2 года', '1095', '24 месяцев', 'Три года',
       'Гарантия дистрибьютора 12 мес. с даты отгрузки', '5 лет',
       '1 год от компании ООО Mics Distribution, сервисный центр М-Проект (по серийному номеру)',
       'Срок гарантии 1 год', 'гарантия производителя 2 года', '6 месяца',
       '3 года.', '5 месяцев', 'Гарантия производителя', '1个月', '3года',
       'первый год', '12 МЕСЯЦЕВ',
       '6 месяцев при сохранении полной комплектации и товарного вида',
       'официальная от Samsung по гарантийному талону', '3 Год'],
      dtype=object)

In [321]:
def convert_to_months(value):
    if pd.isna(value):
        return None

    value = str(value).lower()

    if 'лет' in value or 'год' in value or 'year' in value or '年' in value:
        years = re.findall(r'\d+', value)
        if years:
            return int(years[0]) * 12
        if 'один' in value or 'первый' in value or 'oдnh' in value:
            return 12
        if 'три' in value:
            return 36
    elif 'месяц' in value or 'мес' in value or '个月' in value:
        months = re.findall(r'\d+', value)
        if months:
            return int(months[0])
    elif 'дни' in value or 'дней' in value or 'день' in value or 'days' in value or 'day' in value or '天' in value:
        days = re.findall(r'\d+', value)
        if days:
            return int(days[0]) // 30
    elif re.match(r'\d+(\.\d+)?', value):
        return float(value) if '.' in value else int(value)

    return None

df['Гарантийный срок, месяцы'] = df['Гарантийный срок'].apply(convert_to_months)

df.drop(columns=['Гарантийный срок'], inplace=True)

df.to_csv('step16_warranty.tsv', sep='\t', index=False)

df

,"Диагональ экрана, дюймы","Потребляемая мощность, Вт",Число портов HDMI,"Вес, кг","Макс. частота обновления, Гц",Изогнутый экран,Контрастность,Соотношение сторон,"Время отклика, мс",Web-камера,...,Установка монитора_Крепление на стену,Установка монитора_На подставку,Регулировки_Вращение,Регулировки_Наклон,Регулировки_Поворот,Регулировки_Регулируемая высота,"Ширина, мм","Высота, мм","Глубина, мм","Гарантийный срок, месяцы"
0,34.0,24.0,2.0,6.0,180.0,True,3000.0,2.333333,1.0,False,...,False,True,True,True,True,True,811.0,510.0,210.0,12.0
1,27.0,NaN,1.0,4.0,165.0,False,10001.0,1.777778,1.0,False,...,False,True,False,True,False,False,452.0,612.0,185.0,12.0
2,24.0,30.0,1.0,3.5,180.0,False,10000.0,1.777778,1.0,False,...,False,True,False,True,False,False,NaN,NaN,NaN,12.0
3,23.8,30.0,1.0,3.0,100.0,False,1100.0,1.777778,1.0,False,...,True,True,False,True,False,False,NaN,NaN,NaN,12.0
4,27.0,35.0,NaN,4.0,75.0,False,NaN,1.777778,8.0,False,...,True,True,False,False,False,False,NaN,NaN,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3841,27.0,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,False,...,False,False,False,False,False,False,NaN,NaN,NaN,NaN
3842,31.5,30.0,2.0,7.5,75.0,False,3000.0,1.777778,4.0,False,...,True,True,False,False,False,False,715.0,514.0,248.0,NaN
3843,32.0,33.0,1.0,6.6,165.0,True,3000.0,1.777778,2.0,False,...,True,True,True,True,False,True,785.0,120.0,505.0,6.0
3844,23.8,36.0,1.0,3.7,75.0,False,1000.0,1.777778,5.0,True,...,True,True,False,True,True,True,NaN,NaN,NaN,NaN
3845,21.5,NaN,2.0,5.0,60.0,False,1000.0,1.777778,5.0,False,...,False,True,False,True,False,False,489.5,391.6,183.0,36.0

### Преобразуем Гарантию OZON

In [322]:
df = pd.read_csv('step16_warranty.tsv', sep='\t')

In [323]:
df['Гарантия OZON'].unique()

array([nan, '1 год'], dtype=object)

In [324]:
def is_present(value):
    if pd.isna(value):
        return False

    value = value.strip().lower()
    if '1 год' in value:
        return True
    else:
        return None

df['Гарантия OZON'] = df['Гарантия OZON'].apply(is_present)

df.to_csv('step17_ozon_warranty.tsv', sep='\t', index=False)

df

,"Диагональ экрана, дюймы","Потребляемая мощность, Вт",Число портов HDMI,"Вес, кг","Макс. частота обновления, Гц",Изогнутый экран,Контрастность,Соотношение сторон,"Время отклика, мс",Web-камера,...,Установка монитора_Крепление на стену,Установка монитора_На подставку,Регулировки_Вращение,Регулировки_Наклон,Регулировки_Поворот,Регулировки_Регулируемая высота,"Ширина, мм","Высота, мм","Глубина, мм","Гарантийный срок, месяцы"
0,34.0,24.0,2.0,6.0,180.0,True,3000.0,2.333333,1.0,False,...,False,True,True,True,True,True,811.0,510.0,210.0,12.0
1,27.0,NaN,1.0,4.0,165.0,False,10001.0,1.777778,1.0,False,...,False,True,False,True,False,False,452.0,612.0,185.0,12.0
2,24.0,30.0,1.0,3.5,180.0,False,10000.0,1.777778,1.0,False,...,False,True,False,True,False,False,NaN,NaN,NaN,12.0
3,23.8,30.0,1.0,3.0,100.0,False,1100.0,1.777778,1.0,False,...,True,True,False,True,False,False,NaN,NaN,NaN,12.0
4,27.0,35.0,NaN,4.0,75.0,False,NaN,1.777778,8.0,False,...,True,True,False,False,False,False,NaN,NaN,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3841,27.0,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,False,...,False,False,False,False,False,False,NaN,NaN,NaN,NaN
3842,31.5,30.0,2.0,7.5,75.0,False,3000.0,1.777778,4.0,False,...,True,True,False,False,False,False,715.0,514.0,248.0,NaN
3843,32.0,33.0,1.0,6.6,165.0,True,3000.0,1.777778,2.0,False,...,True,True,True,True,False,True,785.0,120.0,505.0,6.0
3844,23.8,36.0,1.0,3.7,75.0,False,1000.0,1.777778,5.0,True,...,True,True,False,True,True,True,NaN,NaN,NaN,NaN
3845,21.5,NaN,2.0,5.0,60.0,False,1000.0,1.777778,5.0,False,...,False,True,False,True,False,False,489.5,391.6,183.0,36.0

### Преобразуем столбец Продавец

In [325]:
df = pd.read_csv('step17_ozon_warranty.tsv', sep='\t')

In [326]:
def extract_seller_num(seller):
    if seller == "mvideo":
        return 49083
    if seller == "eldorado":
        return 49178
    if seller == "holodilnik":
        return 17817
    if seller == "hobot":
        return 180789
    if seller.isnumeric():
        return seller
    return int(seller[seller.rindex('-') + 1:])

df['Продавец'] = df['Продавец'].apply(extract_seller_num)

df.to_csv('step18_seller.tsv', sep='\t', index=False)

df

,"Диагональ экрана, дюймы","Потребляемая мощность, Вт",Число портов HDMI,"Вес, кг","Макс. частота обновления, Гц",Изогнутый экран,Контрастность,Соотношение сторон,"Время отклика, мс",Web-камера,...,Установка монитора_Крепление на стену,Установка монитора_На подставку,Регулировки_Вращение,Регулировки_Наклон,Регулировки_Поворот,Регулировки_Регулируемая высота,"Ширина, мм","Высота, мм","Глубина, мм","Гарантийный срок, месяцы"
0,34.0,24.0,2.0,6.0,180.0,True,3000.0,2.333333,1.0,False,...,False,True,True,True,True,True,811.0,510.0,210.0,12.0
1,27.0,NaN,1.0,4.0,165.0,False,10001.0,1.777778,1.0,False,...,False,True,False,True,False,False,452.0,612.0,185.0,12.0
2,24.0,30.0,1.0,3.5,180.0,False,10000.0,1.777778,1.0,False,...,False,True,False,True,False,False,NaN,NaN,NaN,12.0
3,23.8,30.0,1.0,3.0,100.0,False,1100.0,1.777778,1.0,False,...,True,True,False,True,False,False,NaN,NaN,NaN,12.0
4,27.0,35.0,NaN,4.0,75.0,False,NaN,1.777778,8.0,False,...,True,True,False,False,False,False,NaN,NaN,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3841,27.0,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,False,...,False,False,False,False,False,False,NaN,NaN,NaN,NaN
3842,31.5,30.0,2.0,7.5,75.0,False,3000.0,1.777778,4.0,False,...,True,True,False,False,False,False,715.0,514.0,248.0,NaN
3843,32.0,33.0,1.0,6.6,165.0,True,3000.0,1.777778,2.0,False,...,True,True,True,True,False,True,785.0,120.0,505.0,6.0
3844,23.8,36.0,1.0,3.7,75.0,False,1000.0,1.777778,5.0,True,...,True,True,False,True,True,True,NaN,NaN,NaN,NaN
3845,21.5,NaN,2.0,5.0,60.0,False,1000.0,1.777778,5.0,False,...,False,True,False,True,False,False,489.5,391.6,183.0,36.0

### Сохраняем итоговый результат

In [353]:
df = pd.read_csv('step18_seller.tsv', sep='\t')
df.to_csv('final_data.tsv', sep='\t', index=False)